/*
xAI's REST API

REST API for xAI compatible with other providers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xai

import (
	"encoding/json"
	"fmt"
)

// checks if the CompactionOutputItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompactionOutputItem{}

// CompactionOutputItem A compaction item from a previous `/v1/responses/compact` call.  Accepted as input in `/v1/responses` calls. Clients must treat `encrypted_content` as opaque — do not parse or depend on its internal structure.
type CompactionOutputItem struct {
	// The encrypted content of the compacted conversation.
	EncryptedContent string `json:"encrypted_content"`
	// The unique ID of the compaction item (e.g. `cmp_<uuid>`).
	Id NullableString `json:"id,omitempty"`
	// The type of the item. Always `\"compaction\"`.
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _CompactionOutputItem CompactionOutputItem

// NewCompactionOutputItem instantiates a new CompactionOutputItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompactionOutputItem(encryptedContent string, type_ string) *CompactionOutputItem {
	this := CompactionOutputItem{}
	this.EncryptedContent = encryptedContent
	this.Type = type_
	return &this
}

// NewCompactionOutputItemWithDefaults instantiates a new CompactionOutputItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompactionOutputItemWithDefaults() *CompactionOutputItem {
	this := CompactionOutputItem{}
	return &this
}

// GetEncryptedContent returns the EncryptedContent field value
func (o *CompactionOutputItem) GetEncryptedContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EncryptedContent
}

// GetEncryptedContentOk returns a tuple with the EncryptedContent field value
// and a boolean to check if the value has been set.
func (o *CompactionOutputItem) GetEncryptedContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncryptedContent, true
}

// SetEncryptedContent sets field value
func (o *CompactionOutputItem) SetEncryptedContent(v string) {
	o.EncryptedContent = v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompactionOutputItem) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompactionOutputItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *CompactionOutputItem) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *CompactionOutputItem) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *CompactionOutputItem) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *CompactionOutputItem) UnsetId() {
	o.Id.Unset()
}

// GetType returns the Type field value
func (o *CompactionOutputItem) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CompactionOutputItem) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CompactionOutputItem) SetType(v string) {
	o.Type = v
}

func (o CompactionOutputItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompactionOutputItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["encrypted_content"] = o.EncryptedContent
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CompactionOutputItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"encrypted_content",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompactionOutputItem := _CompactionOutputItem{}

	err = json.Unmarshal(data, &varCompactionOutputItem)

	if err != nil {
		return err
	}

	*o = CompactionOutputItem(varCompactionOutputItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "encrypted_content")
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCompactionOutputItem struct {
	value *CompactionOutputItem
	isSet bool
}

func (v NullableCompactionOutputItem) Get() *CompactionOutputItem {
	return v.value
}

func (v *NullableCompactionOutputItem) Set(val *CompactionOutputItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCompactionOutputItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCompactionOutputItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompactionOutputItem(val *CompactionOutputItem) *NullableCompactionOutputItem {
	return &NullableCompactionOutputItem{value: val, isSet: true}
}

func (v NullableCompactionOutputItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompactionOutputItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
