/*
xAI's REST API

REST API for xAI compatible with other providers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xai

import (
	"encoding/json"
	"fmt"
)

// checks if the CompactUsageInputTokensDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompactUsageInputTokensDetails{}

// CompactUsageInputTokensDetails Breakdown of input tokens for a compaction call.
type CompactUsageInputTokensDetails struct {
	// Number of input tokens that were served from the prompt cache.
	CachedTokens int32 `json:"cached_tokens"`
	AdditionalProperties map[string]interface{}
}

type _CompactUsageInputTokensDetails CompactUsageInputTokensDetails

// NewCompactUsageInputTokensDetails instantiates a new CompactUsageInputTokensDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompactUsageInputTokensDetails(cachedTokens int32) *CompactUsageInputTokensDetails {
	this := CompactUsageInputTokensDetails{}
	this.CachedTokens = cachedTokens
	return &this
}

// NewCompactUsageInputTokensDetailsWithDefaults instantiates a new CompactUsageInputTokensDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompactUsageInputTokensDetailsWithDefaults() *CompactUsageInputTokensDetails {
	this := CompactUsageInputTokensDetails{}
	return &this
}

// GetCachedTokens returns the CachedTokens field value
func (o *CompactUsageInputTokensDetails) GetCachedTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CachedTokens
}

// GetCachedTokensOk returns a tuple with the CachedTokens field value
// and a boolean to check if the value has been set.
func (o *CompactUsageInputTokensDetails) GetCachedTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CachedTokens, true
}

// SetCachedTokens sets field value
func (o *CompactUsageInputTokensDetails) SetCachedTokens(v int32) {
	o.CachedTokens = v
}

func (o CompactUsageInputTokensDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompactUsageInputTokensDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cached_tokens"] = o.CachedTokens

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CompactUsageInputTokensDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cached_tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompactUsageInputTokensDetails := _CompactUsageInputTokensDetails{}

	err = json.Unmarshal(data, &varCompactUsageInputTokensDetails)

	if err != nil {
		return err
	}

	*o = CompactUsageInputTokensDetails(varCompactUsageInputTokensDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cached_tokens")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCompactUsageInputTokensDetails struct {
	value *CompactUsageInputTokensDetails
	isSet bool
}

func (v NullableCompactUsageInputTokensDetails) Get() *CompactUsageInputTokensDetails {
	return v.value
}

func (v *NullableCompactUsageInputTokensDetails) Set(val *CompactUsageInputTokensDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCompactUsageInputTokensDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCompactUsageInputTokensDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompactUsageInputTokensDetails(val *CompactUsageInputTokensDetails) *NullableCompactUsageInputTokensDetails {
	return &NullableCompactUsageInputTokensDetails{value: val, isSet: true}
}

func (v NullableCompactUsageInputTokensDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompactUsageInputTokensDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
