/*
xAI's REST API

REST API for xAI compatible with other providers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xai

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelInputContentItemOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelInputContentItemOneOf{}

// ModelInputContentItemOneOf Text input.
type ModelInputContentItemOneOf struct {
	// Text input.
	Text string `json:"text"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _ModelInputContentItemOneOf ModelInputContentItemOneOf

// NewModelInputContentItemOneOf instantiates a new ModelInputContentItemOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelInputContentItemOneOf(text string, type_ string) *ModelInputContentItemOneOf {
	this := ModelInputContentItemOneOf{}
	this.Text = text
	this.Type = type_
	return &this
}

// NewModelInputContentItemOneOfWithDefaults instantiates a new ModelInputContentItemOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelInputContentItemOneOfWithDefaults() *ModelInputContentItemOneOf {
	this := ModelInputContentItemOneOf{}
	return &this
}

// GetText returns the Text field value
func (o *ModelInputContentItemOneOf) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *ModelInputContentItemOneOf) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *ModelInputContentItemOneOf) SetText(v string) {
	o.Text = v
}

// GetType returns the Type field value
func (o *ModelInputContentItemOneOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ModelInputContentItemOneOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ModelInputContentItemOneOf) SetType(v string) {
	o.Type = v
}

func (o ModelInputContentItemOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelInputContentItemOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelInputContentItemOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelInputContentItemOneOf := _ModelInputContentItemOneOf{}

	err = json.Unmarshal(data, &varModelInputContentItemOneOf)

	if err != nil {
		return err
	}

	*o = ModelInputContentItemOneOf(varModelInputContentItemOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "text")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelInputContentItemOneOf struct {
	value *ModelInputContentItemOneOf
	isSet bool
}

func (v NullableModelInputContentItemOneOf) Get() *ModelInputContentItemOneOf {
	return v.value
}

func (v *NullableModelInputContentItemOneOf) Set(val *ModelInputContentItemOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableModelInputContentItemOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableModelInputContentItemOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelInputContentItemOneOf(val *ModelInputContentItemOneOf) *NullableModelInputContentItemOneOf {
	return &NullableModelInputContentItemOneOf{value: val, isSet: true}
}

func (v NullableModelInputContentItemOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelInputContentItemOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
