/*
xAI's REST API

REST API for xAI compatible with other providers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xai

import (
	"encoding/json"
)

// checks if the HybridRetrieval type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HybridRetrieval{}

// HybridRetrieval Document search using a combination of keyword and semantic search.
type HybridRetrieval struct {
	// Which reranker to use to limit results to the desired value.
	Reranker NullableHybridReranker `json:"reranker,omitempty"`
	// Additional multiplier to requested search limit. Valid range is [1, 100]. Defaults to 1 when unset.
	SearchMultiplier NullableInt32 `json:"search_multiplier,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HybridRetrieval HybridRetrieval

// NewHybridRetrieval instantiates a new HybridRetrieval object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHybridRetrieval() *HybridRetrieval {
	this := HybridRetrieval{}
	return &this
}

// NewHybridRetrievalWithDefaults instantiates a new HybridRetrieval object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHybridRetrievalWithDefaults() *HybridRetrieval {
	this := HybridRetrieval{}
	return &this
}

// GetReranker returns the Reranker field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HybridRetrieval) GetReranker() HybridReranker {
	if o == nil || IsNil(o.Reranker.Get()) {
		var ret HybridReranker
		return ret
	}
	return *o.Reranker.Get()
}

// GetRerankerOk returns a tuple with the Reranker field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HybridRetrieval) GetRerankerOk() (*HybridReranker, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reranker.Get(), o.Reranker.IsSet()
}

// HasReranker returns a boolean if a field has been set.
func (o *HybridRetrieval) HasReranker() bool {
	if o != nil && o.Reranker.IsSet() {
		return true
	}

	return false
}

// SetReranker gets a reference to the given NullableHybridReranker and assigns it to the Reranker field.
func (o *HybridRetrieval) SetReranker(v HybridReranker) {
	o.Reranker.Set(&v)
}
// SetRerankerNil sets the value for Reranker to be an explicit nil
func (o *HybridRetrieval) SetRerankerNil() {
	o.Reranker.Set(nil)
}

// UnsetReranker ensures that no value is present for Reranker, not even an explicit nil
func (o *HybridRetrieval) UnsetReranker() {
	o.Reranker.Unset()
}

// GetSearchMultiplier returns the SearchMultiplier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HybridRetrieval) GetSearchMultiplier() int32 {
	if o == nil || IsNil(o.SearchMultiplier.Get()) {
		var ret int32
		return ret
	}
	return *o.SearchMultiplier.Get()
}

// GetSearchMultiplierOk returns a tuple with the SearchMultiplier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HybridRetrieval) GetSearchMultiplierOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SearchMultiplier.Get(), o.SearchMultiplier.IsSet()
}

// HasSearchMultiplier returns a boolean if a field has been set.
func (o *HybridRetrieval) HasSearchMultiplier() bool {
	if o != nil && o.SearchMultiplier.IsSet() {
		return true
	}

	return false
}

// SetSearchMultiplier gets a reference to the given NullableInt32 and assigns it to the SearchMultiplier field.
func (o *HybridRetrieval) SetSearchMultiplier(v int32) {
	o.SearchMultiplier.Set(&v)
}
// SetSearchMultiplierNil sets the value for SearchMultiplier to be an explicit nil
func (o *HybridRetrieval) SetSearchMultiplierNil() {
	o.SearchMultiplier.Set(nil)
}

// UnsetSearchMultiplier ensures that no value is present for SearchMultiplier, not even an explicit nil
func (o *HybridRetrieval) UnsetSearchMultiplier() {
	o.SearchMultiplier.Unset()
}

func (o HybridRetrieval) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HybridRetrieval) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Reranker.IsSet() {
		toSerialize["reranker"] = o.Reranker.Get()
	}
	if o.SearchMultiplier.IsSet() {
		toSerialize["search_multiplier"] = o.SearchMultiplier.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HybridRetrieval) UnmarshalJSON(data []byte) (err error) {
	varHybridRetrieval := _HybridRetrieval{}

	err = json.Unmarshal(data, &varHybridRetrieval)

	if err != nil {
		return err
	}

	*o = HybridRetrieval(varHybridRetrieval)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "reranker")
		delete(additionalProperties, "search_multiplier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHybridRetrieval struct {
	value *HybridRetrieval
	isSet bool
}

func (v NullableHybridRetrieval) Get() *HybridRetrieval {
	return v.value
}

func (v *NullableHybridRetrieval) Set(val *HybridRetrieval) {
	v.value = val
	v.isSet = true
}

func (v NullableHybridRetrieval) IsSet() bool {
	return v.isSet
}

func (v *NullableHybridRetrieval) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHybridRetrieval(val *HybridRetrieval) *NullableHybridRetrieval {
	return &NullableHybridRetrieval{value: val, isSet: true}
}

func (v NullableHybridRetrieval) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHybridRetrieval) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
