/*
xAI's REST API

REST API for xAI compatible with other providers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xai

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelRequest{}

// ModelRequest The request body for `/v1/responses` endpoint.
type ModelRequest struct {
	// (Unsupported) Whether to process the response asynchronously in the background.
	Background NullableBool `json:"background,omitempty"`
	// Optional context-management directives (e.g. compaction). Parsed but not yet executed.
	ContextManagement []interface{} `json:"context_management,omitempty"`
	// What additional output data to include in the response. Currently the only supported value is `reasoning.encrypted_content` which returns an encrypted version of the reasoning tokens.
	Include []string `json:"include,omitempty"`
	// The input passed to the model. Can be text, image or file.
	Input ModelInput `json:"input"`
	// An alternate way to specify the system prompt. Note that this cannot be used alongside `previous_response_id`, where the system prompt of the previous message will be used.
	Instructions NullableString `json:"instructions,omitempty"`
	// Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message. Not supported by models `grok-4.20` and newer; the field will be silently ignored if set.
	Logprobs NullableBool `json:"logprobs,omitempty"`
	// Max number of tokens that can be generated in a response. This includes both output and reasoning tokens.
	MaxOutputTokens NullableInt32 `json:"max_output_tokens,omitempty"`
	// Maximum number of agentic tool calling turns allowed for this request. If not set, defaults to the server's global cap. This parameter will be ignored for any non-agentic requests.
	MaxTurns NullableInt32 `json:"max_turns,omitempty"`
	Metadata interface{}   `json:"metadata,omitempty"`
	// Min-p sampling: tokens whose probability is below `min_p` times the probability of the most likely token are excluded from sampling. Disabled when unset.
	MinP NullableFloat32 `json:"min_p,omitempty"`
	// Model name for the model to use. Obtainable from <https://console.x.ai/team/default/models> or <https://docs.x.ai/docs/models>.
	Model *string `json:"model,omitempty"`
	// Whether to allow the model to run parallel tool calls.
	ParallelToolCalls NullableBool `json:"parallel_tool_calls,omitempty"`
	// The ID of the previous response from the model.
	PreviousResponseId NullableString `json:"previous_response_id,omitempty"`
	// Plumbed to x-grok-conv-id for Open Responses compatibility, used for routing.
	PromptCacheKey NullableString `json:"prompt_cache_key,omitempty"`
	// Reasoning configuration. Only for reasoning models.
	Reasoning NullableReasoningConfiguration `json:"reasoning,omitempty"`
	// Set the parameters to be used for searched data. Takes precedence over `web_search_preview` tool if specified in the tools.
	SearchParameters NullableSearchParameters `json:"search_parameters,omitempty"`
	// Specifies the processing tier for this request. Set to `\"priority\"` for higher scheduling priority at a higher token price. Valid values: `\"auto\"` (default), `\"priority\"`.
	ServiceTier NullableServiceTier `json:"service_tier,omitempty"`
	// Whether to store the input message(s) and model response for later retrieval.
	Store NullableBool `json:"store,omitempty"`
	// If set, partial message deltas will be sent. Tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a `data: [DONE]` message.
	Stream NullableBool `json:"stream,omitempty"`
	// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
	Temperature NullableFloat32 `json:"temperature,omitempty"`
	// Settings for customizing a text response from the model.
	Text NullableModelResponseConfiguration `json:"text,omitempty"`
	// Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. auto means the model can pick between generating a message or calling one or more tools. required means the model must call one or more tools. Specifying a particular tool via `{\"type\": \"function\", \"function\": {\"name\": \"my_function\"}}` forces the model to call that tool. `none` is the default when no tools are present. `auto` is the default if tools are present.
	ToolChoice NullableModelToolChoice `json:"tool_choice,omitempty"`
	// A list of tools the model may call in JSON-schema. Currently, only functions and web search are supported as tools. A max of 128 tools are supported.`web_search_preview` tool, if specified, will be overridden by `search_parameters`.
	Tools []ModelTool `json:"tools,omitempty"`
	// Top-k sampling: only the `top_k` most probable tokens are considered at each sampling step. Disabled when unset.
	TopK NullableInt32 `json:"top_k,omitempty"`
	// An integer between 0 and 8 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used. Not supported by models `grok-4.20` and newer; the field will be silently ignored if set.
	TopLogprobs NullableInt32 `json:"top_logprobs,omitempty"`
	// An alternative to sampling with `temperature`, called nucleus sampling, where the model considers the results of the tokens with `top_p` probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. It is generally recommended to alter this or `temperature` but not both.
	TopP NullableFloat32 `json:"top_p,omitempty"`
	// Not supported. Only maintained for compatibility reasons.
	Truncation NullableString `json:"truncation,omitempty"`
	// A unique identifier representing your end-user, which can help xAI to monitor and detect abuse.
	User                 NullableString `json:"user,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelRequest ModelRequest

// NewModelRequest instantiates a new ModelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelRequest(input ModelInput) *ModelRequest {
	this := ModelRequest{}
	var background bool = false
	this.Background = *NewNullableBool(&background)
	this.Input = input
	var logprobs bool = false
	this.Logprobs = *NewNullableBool(&logprobs)
	var parallelToolCalls bool = true
	this.ParallelToolCalls = *NewNullableBool(&parallelToolCalls)
	var store bool = true
	this.Store = *NewNullableBool(&store)
	var stream bool = false
	this.Stream = *NewNullableBool(&stream)
	var temperature float32 = 1
	this.Temperature = *NewNullableFloat32(&temperature)
	var topP float32 = 1
	this.TopP = *NewNullableFloat32(&topP)
	return &this
}

// NewModelRequestWithDefaults instantiates a new ModelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelRequestWithDefaults() *ModelRequest {
	this := ModelRequest{}
	var background bool = false
	this.Background = *NewNullableBool(&background)
	var logprobs bool = false
	this.Logprobs = *NewNullableBool(&logprobs)
	var parallelToolCalls bool = true
	this.ParallelToolCalls = *NewNullableBool(&parallelToolCalls)
	var store bool = true
	this.Store = *NewNullableBool(&store)
	var stream bool = false
	this.Stream = *NewNullableBool(&stream)
	var temperature float32 = 1
	this.Temperature = *NewNullableFloat32(&temperature)
	var topP float32 = 1
	this.TopP = *NewNullableFloat32(&topP)
	return &this
}

// GetBackground returns the Background field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetBackground() bool {
	if o == nil || IsNil(o.Background.Get()) {
		var ret bool
		return ret
	}
	return *o.Background.Get()
}

// GetBackgroundOk returns a tuple with the Background field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetBackgroundOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Background.Get(), o.Background.IsSet()
}

// HasBackground returns a boolean if a field has been set.
func (o *ModelRequest) HasBackground() bool {
	if o != nil && o.Background.IsSet() {
		return true
	}

	return false
}

// SetBackground gets a reference to the given NullableBool and assigns it to the Background field.
func (o *ModelRequest) SetBackground(v bool) {
	o.Background.Set(&v)
}

// SetBackgroundNil sets the value for Background to be an explicit nil
func (o *ModelRequest) SetBackgroundNil() {
	o.Background.Set(nil)
}

// UnsetBackground ensures that no value is present for Background, not even an explicit nil
func (o *ModelRequest) UnsetBackground() {
	o.Background.Unset()
}

// GetContextManagement returns the ContextManagement field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetContextManagement() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}
	return o.ContextManagement
}

// GetContextManagementOk returns a tuple with the ContextManagement field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetContextManagementOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.ContextManagement) {
		return nil, false
	}
	return o.ContextManagement, true
}

// HasContextManagement returns a boolean if a field has been set.
func (o *ModelRequest) HasContextManagement() bool {
	if o != nil && !IsNil(o.ContextManagement) {
		return true
	}

	return false
}

// SetContextManagement gets a reference to the given []interface{} and assigns it to the ContextManagement field.
func (o *ModelRequest) SetContextManagement(v []interface{}) {
	o.ContextManagement = v
}

// GetInclude returns the Include field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetInclude() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetIncludeOk() ([]string, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return o.Include, true
}

// HasInclude returns a boolean if a field has been set.
func (o *ModelRequest) HasInclude() bool {
	if o != nil && !IsNil(o.Include) {
		return true
	}

	return false
}

// SetInclude gets a reference to the given []string and assigns it to the Include field.
func (o *ModelRequest) SetInclude(v []string) {
	o.Include = v
}

// GetInput returns the Input field value
func (o *ModelRequest) GetInput() ModelInput {
	if o == nil {
		var ret ModelInput
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *ModelRequest) GetInputOk() (*ModelInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *ModelRequest) SetInput(v ModelInput) {
	o.Input = v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions.Get()) {
		var ret string
		return ret
	}
	return *o.Instructions.Get()
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instructions.Get(), o.Instructions.IsSet()
}

// HasInstructions returns a boolean if a field has been set.
func (o *ModelRequest) HasInstructions() bool {
	if o != nil && o.Instructions.IsSet() {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given NullableString and assigns it to the Instructions field.
func (o *ModelRequest) SetInstructions(v string) {
	o.Instructions.Set(&v)
}

// SetInstructionsNil sets the value for Instructions to be an explicit nil
func (o *ModelRequest) SetInstructionsNil() {
	o.Instructions.Set(nil)
}

// UnsetInstructions ensures that no value is present for Instructions, not even an explicit nil
func (o *ModelRequest) UnsetInstructions() {
	o.Instructions.Unset()
}

// GetLogprobs returns the Logprobs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetLogprobs() bool {
	if o == nil || IsNil(o.Logprobs.Get()) {
		var ret bool
		return ret
	}
	return *o.Logprobs.Get()
}

// GetLogprobsOk returns a tuple with the Logprobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetLogprobsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logprobs.Get(), o.Logprobs.IsSet()
}

// HasLogprobs returns a boolean if a field has been set.
func (o *ModelRequest) HasLogprobs() bool {
	if o != nil && o.Logprobs.IsSet() {
		return true
	}

	return false
}

// SetLogprobs gets a reference to the given NullableBool and assigns it to the Logprobs field.
func (o *ModelRequest) SetLogprobs(v bool) {
	o.Logprobs.Set(&v)
}

// SetLogprobsNil sets the value for Logprobs to be an explicit nil
func (o *ModelRequest) SetLogprobsNil() {
	o.Logprobs.Set(nil)
}

// UnsetLogprobs ensures that no value is present for Logprobs, not even an explicit nil
func (o *ModelRequest) UnsetLogprobs() {
	o.Logprobs.Unset()
}

// GetMaxOutputTokens returns the MaxOutputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetMaxOutputTokens() int32 {
	if o == nil || IsNil(o.MaxOutputTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxOutputTokens.Get()
}

// GetMaxOutputTokensOk returns a tuple with the MaxOutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetMaxOutputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxOutputTokens.Get(), o.MaxOutputTokens.IsSet()
}

// HasMaxOutputTokens returns a boolean if a field has been set.
func (o *ModelRequest) HasMaxOutputTokens() bool {
	if o != nil && o.MaxOutputTokens.IsSet() {
		return true
	}

	return false
}

// SetMaxOutputTokens gets a reference to the given NullableInt32 and assigns it to the MaxOutputTokens field.
func (o *ModelRequest) SetMaxOutputTokens(v int32) {
	o.MaxOutputTokens.Set(&v)
}

// SetMaxOutputTokensNil sets the value for MaxOutputTokens to be an explicit nil
func (o *ModelRequest) SetMaxOutputTokensNil() {
	o.MaxOutputTokens.Set(nil)
}

// UnsetMaxOutputTokens ensures that no value is present for MaxOutputTokens, not even an explicit nil
func (o *ModelRequest) UnsetMaxOutputTokens() {
	o.MaxOutputTokens.Unset()
}

// GetMaxTurns returns the MaxTurns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetMaxTurns() int32 {
	if o == nil || IsNil(o.MaxTurns.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxTurns.Get()
}

// GetMaxTurnsOk returns a tuple with the MaxTurns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetMaxTurnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTurns.Get(), o.MaxTurns.IsSet()
}

// HasMaxTurns returns a boolean if a field has been set.
func (o *ModelRequest) HasMaxTurns() bool {
	if o != nil && o.MaxTurns.IsSet() {
		return true
	}

	return false
}

// SetMaxTurns gets a reference to the given NullableInt32 and assigns it to the MaxTurns field.
func (o *ModelRequest) SetMaxTurns(v int32) {
	o.MaxTurns.Set(&v)
}

// SetMaxTurnsNil sets the value for MaxTurns to be an explicit nil
func (o *ModelRequest) SetMaxTurnsNil() {
	o.MaxTurns.Set(nil)
}

// UnsetMaxTurns ensures that no value is present for MaxTurns, not even an explicit nil
func (o *ModelRequest) UnsetMaxTurns() {
	o.MaxTurns.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ModelRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *ModelRequest) SetMetadata(v interface{}) {
	o.Metadata = v
}

// GetMinP returns the MinP field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetMinP() float32 {
	if o == nil || IsNil(o.MinP.Get()) {
		var ret float32
		return ret
	}
	return *o.MinP.Get()
}

// GetMinPOk returns a tuple with the MinP field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetMinPOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinP.Get(), o.MinP.IsSet()
}

// HasMinP returns a boolean if a field has been set.
func (o *ModelRequest) HasMinP() bool {
	if o != nil && o.MinP.IsSet() {
		return true
	}

	return false
}

// SetMinP gets a reference to the given NullableFloat32 and assigns it to the MinP field.
func (o *ModelRequest) SetMinP(v float32) {
	o.MinP.Set(&v)
}

// SetMinPNil sets the value for MinP to be an explicit nil
func (o *ModelRequest) SetMinPNil() {
	o.MinP.Set(nil)
}

// UnsetMinP ensures that no value is present for MinP, not even an explicit nil
func (o *ModelRequest) UnsetMinP() {
	o.MinP.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *ModelRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *ModelRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *ModelRequest) SetModel(v string) {
	o.Model = &v
}

// GetParallelToolCalls returns the ParallelToolCalls field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetParallelToolCalls() bool {
	if o == nil || IsNil(o.ParallelToolCalls.Get()) {
		var ret bool
		return ret
	}
	return *o.ParallelToolCalls.Get()
}

// GetParallelToolCallsOk returns a tuple with the ParallelToolCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetParallelToolCallsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParallelToolCalls.Get(), o.ParallelToolCalls.IsSet()
}

// HasParallelToolCalls returns a boolean if a field has been set.
func (o *ModelRequest) HasParallelToolCalls() bool {
	if o != nil && o.ParallelToolCalls.IsSet() {
		return true
	}

	return false
}

// SetParallelToolCalls gets a reference to the given NullableBool and assigns it to the ParallelToolCalls field.
func (o *ModelRequest) SetParallelToolCalls(v bool) {
	o.ParallelToolCalls.Set(&v)
}

// SetParallelToolCallsNil sets the value for ParallelToolCalls to be an explicit nil
func (o *ModelRequest) SetParallelToolCallsNil() {
	o.ParallelToolCalls.Set(nil)
}

// UnsetParallelToolCalls ensures that no value is present for ParallelToolCalls, not even an explicit nil
func (o *ModelRequest) UnsetParallelToolCalls() {
	o.ParallelToolCalls.Unset()
}

// GetPreviousResponseId returns the PreviousResponseId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetPreviousResponseId() string {
	if o == nil || IsNil(o.PreviousResponseId.Get()) {
		var ret string
		return ret
	}
	return *o.PreviousResponseId.Get()
}

// GetPreviousResponseIdOk returns a tuple with the PreviousResponseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetPreviousResponseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousResponseId.Get(), o.PreviousResponseId.IsSet()
}

// HasPreviousResponseId returns a boolean if a field has been set.
func (o *ModelRequest) HasPreviousResponseId() bool {
	if o != nil && o.PreviousResponseId.IsSet() {
		return true
	}

	return false
}

// SetPreviousResponseId gets a reference to the given NullableString and assigns it to the PreviousResponseId field.
func (o *ModelRequest) SetPreviousResponseId(v string) {
	o.PreviousResponseId.Set(&v)
}

// SetPreviousResponseIdNil sets the value for PreviousResponseId to be an explicit nil
func (o *ModelRequest) SetPreviousResponseIdNil() {
	o.PreviousResponseId.Set(nil)
}

// UnsetPreviousResponseId ensures that no value is present for PreviousResponseId, not even an explicit nil
func (o *ModelRequest) UnsetPreviousResponseId() {
	o.PreviousResponseId.Unset()
}

// GetPromptCacheKey returns the PromptCacheKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetPromptCacheKey() string {
	if o == nil || IsNil(o.PromptCacheKey.Get()) {
		var ret string
		return ret
	}
	return *o.PromptCacheKey.Get()
}

// GetPromptCacheKeyOk returns a tuple with the PromptCacheKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetPromptCacheKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptCacheKey.Get(), o.PromptCacheKey.IsSet()
}

// HasPromptCacheKey returns a boolean if a field has been set.
func (o *ModelRequest) HasPromptCacheKey() bool {
	if o != nil && o.PromptCacheKey.IsSet() {
		return true
	}

	return false
}

// SetPromptCacheKey gets a reference to the given NullableString and assigns it to the PromptCacheKey field.
func (o *ModelRequest) SetPromptCacheKey(v string) {
	o.PromptCacheKey.Set(&v)
}

// SetPromptCacheKeyNil sets the value for PromptCacheKey to be an explicit nil
func (o *ModelRequest) SetPromptCacheKeyNil() {
	o.PromptCacheKey.Set(nil)
}

// UnsetPromptCacheKey ensures that no value is present for PromptCacheKey, not even an explicit nil
func (o *ModelRequest) UnsetPromptCacheKey() {
	o.PromptCacheKey.Unset()
}

// GetReasoning returns the Reasoning field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetReasoning() ReasoningConfiguration {
	if o == nil || IsNil(o.Reasoning.Get()) {
		var ret ReasoningConfiguration
		return ret
	}
	return *o.Reasoning.Get()
}

// GetReasoningOk returns a tuple with the Reasoning field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetReasoningOk() (*ReasoningConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reasoning.Get(), o.Reasoning.IsSet()
}

// HasReasoning returns a boolean if a field has been set.
func (o *ModelRequest) HasReasoning() bool {
	if o != nil && o.Reasoning.IsSet() {
		return true
	}

	return false
}

// SetReasoning gets a reference to the given NullableReasoningConfiguration and assigns it to the Reasoning field.
func (o *ModelRequest) SetReasoning(v ReasoningConfiguration) {
	o.Reasoning.Set(&v)
}

// SetReasoningNil sets the value for Reasoning to be an explicit nil
func (o *ModelRequest) SetReasoningNil() {
	o.Reasoning.Set(nil)
}

// UnsetReasoning ensures that no value is present for Reasoning, not even an explicit nil
func (o *ModelRequest) UnsetReasoning() {
	o.Reasoning.Unset()
}

// GetSearchParameters returns the SearchParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetSearchParameters() SearchParameters {
	if o == nil || IsNil(o.SearchParameters.Get()) {
		var ret SearchParameters
		return ret
	}
	return *o.SearchParameters.Get()
}

// GetSearchParametersOk returns a tuple with the SearchParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetSearchParametersOk() (*SearchParameters, bool) {
	if o == nil {
		return nil, false
	}
	return o.SearchParameters.Get(), o.SearchParameters.IsSet()
}

// HasSearchParameters returns a boolean if a field has been set.
func (o *ModelRequest) HasSearchParameters() bool {
	if o != nil && o.SearchParameters.IsSet() {
		return true
	}

	return false
}

// SetSearchParameters gets a reference to the given NullableSearchParameters and assigns it to the SearchParameters field.
func (o *ModelRequest) SetSearchParameters(v SearchParameters) {
	o.SearchParameters.Set(&v)
}

// SetSearchParametersNil sets the value for SearchParameters to be an explicit nil
func (o *ModelRequest) SetSearchParametersNil() {
	o.SearchParameters.Set(nil)
}

// UnsetSearchParameters ensures that no value is present for SearchParameters, not even an explicit nil
func (o *ModelRequest) UnsetSearchParameters() {
	o.SearchParameters.Unset()
}

// GetServiceTier returns the ServiceTier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetServiceTier() ServiceTier {
	if o == nil || IsNil(o.ServiceTier.Get()) {
		var ret ServiceTier
		return ret
	}
	return *o.ServiceTier.Get()
}

// GetServiceTierOk returns a tuple with the ServiceTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetServiceTierOk() (*ServiceTier, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceTier.Get(), o.ServiceTier.IsSet()
}

// HasServiceTier returns a boolean if a field has been set.
func (o *ModelRequest) HasServiceTier() bool {
	if o != nil && o.ServiceTier.IsSet() {
		return true
	}

	return false
}

// SetServiceTier gets a reference to the given NullableServiceTier and assigns it to the ServiceTier field.
func (o *ModelRequest) SetServiceTier(v ServiceTier) {
	o.ServiceTier.Set(&v)
}

// SetServiceTierNil sets the value for ServiceTier to be an explicit nil
func (o *ModelRequest) SetServiceTierNil() {
	o.ServiceTier.Set(nil)
}

// UnsetServiceTier ensures that no value is present for ServiceTier, not even an explicit nil
func (o *ModelRequest) UnsetServiceTier() {
	o.ServiceTier.Unset()
}

// GetStore returns the Store field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetStore() bool {
	if o == nil || IsNil(o.Store.Get()) {
		var ret bool
		return ret
	}
	return *o.Store.Get()
}

// GetStoreOk returns a tuple with the Store field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetStoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Store.Get(), o.Store.IsSet()
}

// HasStore returns a boolean if a field has been set.
func (o *ModelRequest) HasStore() bool {
	if o != nil && o.Store.IsSet() {
		return true
	}

	return false
}

// SetStore gets a reference to the given NullableBool and assigns it to the Store field.
func (o *ModelRequest) SetStore(v bool) {
	o.Store.Set(&v)
}

// SetStoreNil sets the value for Store to be an explicit nil
func (o *ModelRequest) SetStoreNil() {
	o.Store.Set(nil)
}

// UnsetStore ensures that no value is present for Store, not even an explicit nil
func (o *ModelRequest) UnsetStore() {
	o.Store.Unset()
}

// GetStream returns the Stream field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetStream() bool {
	if o == nil || IsNil(o.Stream.Get()) {
		var ret bool
		return ret
	}
	return *o.Stream.Get()
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetStreamOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stream.Get(), o.Stream.IsSet()
}

// HasStream returns a boolean if a field has been set.
func (o *ModelRequest) HasStream() bool {
	if o != nil && o.Stream.IsSet() {
		return true
	}

	return false
}

// SetStream gets a reference to the given NullableBool and assigns it to the Stream field.
func (o *ModelRequest) SetStream(v bool) {
	o.Stream.Set(&v)
}

// SetStreamNil sets the value for Stream to be an explicit nil
func (o *ModelRequest) SetStreamNil() {
	o.Stream.Set(nil)
}

// UnsetStream ensures that no value is present for Stream, not even an explicit nil
func (o *ModelRequest) UnsetStream() {
	o.Stream.Unset()
}

// GetTemperature returns the Temperature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature.Get()) {
		var ret float32
		return ret
	}
	return *o.Temperature.Get()
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetTemperatureOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Temperature.Get(), o.Temperature.IsSet()
}

// HasTemperature returns a boolean if a field has been set.
func (o *ModelRequest) HasTemperature() bool {
	if o != nil && o.Temperature.IsSet() {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given NullableFloat32 and assigns it to the Temperature field.
func (o *ModelRequest) SetTemperature(v float32) {
	o.Temperature.Set(&v)
}

// SetTemperatureNil sets the value for Temperature to be an explicit nil
func (o *ModelRequest) SetTemperatureNil() {
	o.Temperature.Set(nil)
}

// UnsetTemperature ensures that no value is present for Temperature, not even an explicit nil
func (o *ModelRequest) UnsetTemperature() {
	o.Temperature.Unset()
}

// GetText returns the Text field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetText() ModelResponseConfiguration {
	if o == nil || IsNil(o.Text.Get()) {
		var ret ModelResponseConfiguration
		return ret
	}
	return *o.Text.Get()
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetTextOk() (*ModelResponseConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return o.Text.Get(), o.Text.IsSet()
}

// HasText returns a boolean if a field has been set.
func (o *ModelRequest) HasText() bool {
	if o != nil && o.Text.IsSet() {
		return true
	}

	return false
}

// SetText gets a reference to the given NullableModelResponseConfiguration and assigns it to the Text field.
func (o *ModelRequest) SetText(v ModelResponseConfiguration) {
	o.Text.Set(&v)
}

// SetTextNil sets the value for Text to be an explicit nil
func (o *ModelRequest) SetTextNil() {
	o.Text.Set(nil)
}

// UnsetText ensures that no value is present for Text, not even an explicit nil
func (o *ModelRequest) UnsetText() {
	o.Text.Unset()
}

// GetToolChoice returns the ToolChoice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetToolChoice() ModelToolChoice {
	if o == nil || IsNil(o.ToolChoice.Get()) {
		var ret ModelToolChoice
		return ret
	}
	return *o.ToolChoice.Get()
}

// GetToolChoiceOk returns a tuple with the ToolChoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetToolChoiceOk() (*ModelToolChoice, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToolChoice.Get(), o.ToolChoice.IsSet()
}

// HasToolChoice returns a boolean if a field has been set.
func (o *ModelRequest) HasToolChoice() bool {
	if o != nil && o.ToolChoice.IsSet() {
		return true
	}

	return false
}

// SetToolChoice gets a reference to the given NullableModelToolChoice and assigns it to the ToolChoice field.
func (o *ModelRequest) SetToolChoice(v ModelToolChoice) {
	o.ToolChoice.Set(&v)
}

// SetToolChoiceNil sets the value for ToolChoice to be an explicit nil
func (o *ModelRequest) SetToolChoiceNil() {
	o.ToolChoice.Set(nil)
}

// UnsetToolChoice ensures that no value is present for ToolChoice, not even an explicit nil
func (o *ModelRequest) UnsetToolChoice() {
	o.ToolChoice.Unset()
}

// GetTools returns the Tools field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetTools() []ModelTool {
	if o == nil {
		var ret []ModelTool
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetToolsOk() ([]ModelTool, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *ModelRequest) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []ModelTool and assigns it to the Tools field.
func (o *ModelRequest) SetTools(v []ModelTool) {
	o.Tools = v
}

// GetTopK returns the TopK field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetTopK() int32 {
	if o == nil || IsNil(o.TopK.Get()) {
		var ret int32
		return ret
	}
	return *o.TopK.Get()
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetTopKOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopK.Get(), o.TopK.IsSet()
}

// HasTopK returns a boolean if a field has been set.
func (o *ModelRequest) HasTopK() bool {
	if o != nil && o.TopK.IsSet() {
		return true
	}

	return false
}

// SetTopK gets a reference to the given NullableInt32 and assigns it to the TopK field.
func (o *ModelRequest) SetTopK(v int32) {
	o.TopK.Set(&v)
}

// SetTopKNil sets the value for TopK to be an explicit nil
func (o *ModelRequest) SetTopKNil() {
	o.TopK.Set(nil)
}

// UnsetTopK ensures that no value is present for TopK, not even an explicit nil
func (o *ModelRequest) UnsetTopK() {
	o.TopK.Unset()
}

// GetTopLogprobs returns the TopLogprobs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetTopLogprobs() int32 {
	if o == nil || IsNil(o.TopLogprobs.Get()) {
		var ret int32
		return ret
	}
	return *o.TopLogprobs.Get()
}

// GetTopLogprobsOk returns a tuple with the TopLogprobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetTopLogprobsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopLogprobs.Get(), o.TopLogprobs.IsSet()
}

// HasTopLogprobs returns a boolean if a field has been set.
func (o *ModelRequest) HasTopLogprobs() bool {
	if o != nil && o.TopLogprobs.IsSet() {
		return true
	}

	return false
}

// SetTopLogprobs gets a reference to the given NullableInt32 and assigns it to the TopLogprobs field.
func (o *ModelRequest) SetTopLogprobs(v int32) {
	o.TopLogprobs.Set(&v)
}

// SetTopLogprobsNil sets the value for TopLogprobs to be an explicit nil
func (o *ModelRequest) SetTopLogprobsNil() {
	o.TopLogprobs.Set(nil)
}

// UnsetTopLogprobs ensures that no value is present for TopLogprobs, not even an explicit nil
func (o *ModelRequest) UnsetTopLogprobs() {
	o.TopLogprobs.Unset()
}

// GetTopP returns the TopP field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetTopP() float32 {
	if o == nil || IsNil(o.TopP.Get()) {
		var ret float32
		return ret
	}
	return *o.TopP.Get()
}

// GetTopPOk returns a tuple with the TopP field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetTopPOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopP.Get(), o.TopP.IsSet()
}

// HasTopP returns a boolean if a field has been set.
func (o *ModelRequest) HasTopP() bool {
	if o != nil && o.TopP.IsSet() {
		return true
	}

	return false
}

// SetTopP gets a reference to the given NullableFloat32 and assigns it to the TopP field.
func (o *ModelRequest) SetTopP(v float32) {
	o.TopP.Set(&v)
}

// SetTopPNil sets the value for TopP to be an explicit nil
func (o *ModelRequest) SetTopPNil() {
	o.TopP.Set(nil)
}

// UnsetTopP ensures that no value is present for TopP, not even an explicit nil
func (o *ModelRequest) UnsetTopP() {
	o.TopP.Unset()
}

// GetTruncation returns the Truncation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetTruncation() string {
	if o == nil || IsNil(o.Truncation.Get()) {
		var ret string
		return ret
	}
	return *o.Truncation.Get()
}

// GetTruncationOk returns a tuple with the Truncation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetTruncationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Truncation.Get(), o.Truncation.IsSet()
}

// HasTruncation returns a boolean if a field has been set.
func (o *ModelRequest) HasTruncation() bool {
	if o != nil && o.Truncation.IsSet() {
		return true
	}

	return false
}

// SetTruncation gets a reference to the given NullableString and assigns it to the Truncation field.
func (o *ModelRequest) SetTruncation(v string) {
	o.Truncation.Set(&v)
}

// SetTruncationNil sets the value for Truncation to be an explicit nil
func (o *ModelRequest) SetTruncationNil() {
	o.Truncation.Set(nil)
}

// UnsetTruncation ensures that no value is present for Truncation, not even an explicit nil
func (o *ModelRequest) UnsetTruncation() {
	o.Truncation.Unset()
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelRequest) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRequest) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *ModelRequest) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *ModelRequest) SetUser(v string) {
	o.User.Set(&v)
}

// SetUserNil sets the value for User to be an explicit nil
func (o *ModelRequest) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *ModelRequest) UnsetUser() {
	o.User.Unset()
}

func (o ModelRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Background.IsSet() {
		toSerialize["background"] = o.Background.Get()
	}
	if o.ContextManagement != nil {
		toSerialize["context_management"] = o.ContextManagement
	}
	if o.Include != nil {
		toSerialize["include"] = o.Include
	}
	toSerialize["input"] = o.Input
	if o.Instructions.IsSet() {
		toSerialize["instructions"] = o.Instructions.Get()
	}
	if o.Logprobs.IsSet() {
		toSerialize["logprobs"] = o.Logprobs.Get()
	}
	if o.MaxOutputTokens.IsSet() {
		toSerialize["max_output_tokens"] = o.MaxOutputTokens.Get()
	}
	if o.MaxTurns.IsSet() {
		toSerialize["max_turns"] = o.MaxTurns.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.MinP.IsSet() {
		toSerialize["min_p"] = o.MinP.Get()
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if o.ParallelToolCalls.IsSet() {
		toSerialize["parallel_tool_calls"] = o.ParallelToolCalls.Get()
	}
	if o.PreviousResponseId.IsSet() {
		toSerialize["previous_response_id"] = o.PreviousResponseId.Get()
	}
	if o.PromptCacheKey.IsSet() {
		toSerialize["prompt_cache_key"] = o.PromptCacheKey.Get()
	}
	if o.Reasoning.IsSet() {
		toSerialize["reasoning"] = o.Reasoning.Get()
	}
	if o.SearchParameters.IsSet() {
		toSerialize["search_parameters"] = o.SearchParameters.Get()
	}
	if o.ServiceTier.IsSet() {
		toSerialize["service_tier"] = o.ServiceTier.Get()
	}
	if o.Store.IsSet() {
		toSerialize["store"] = o.Store.Get()
	}
	if o.Stream.IsSet() {
		toSerialize["stream"] = o.Stream.Get()
	}
	if o.Temperature.IsSet() {
		toSerialize["temperature"] = o.Temperature.Get()
	}
	if o.Text.IsSet() {
		toSerialize["text"] = o.Text.Get()
	}
	if o.ToolChoice.IsSet() {
		toSerialize["tool_choice"] = o.ToolChoice.Get()
	}
	if o.Tools != nil {
		toSerialize["tools"] = o.Tools
	}
	if o.TopK.IsSet() {
		toSerialize["top_k"] = o.TopK.Get()
	}
	if o.TopLogprobs.IsSet() {
		toSerialize["top_logprobs"] = o.TopLogprobs.Get()
	}
	if o.TopP.IsSet() {
		toSerialize["top_p"] = o.TopP.Get()
	}
	if o.Truncation.IsSet() {
		toSerialize["truncation"] = o.Truncation.Get()
	}
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelRequest := _ModelRequest{}

	err = json.Unmarshal(data, &varModelRequest)

	if err != nil {
		return err
	}

	*o = ModelRequest(varModelRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "background")
		delete(additionalProperties, "context_management")
		delete(additionalProperties, "include")
		delete(additionalProperties, "input")
		delete(additionalProperties, "instructions")
		delete(additionalProperties, "logprobs")
		delete(additionalProperties, "max_output_tokens")
		delete(additionalProperties, "max_turns")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "min_p")
		delete(additionalProperties, "model")
		delete(additionalProperties, "parallel_tool_calls")
		delete(additionalProperties, "previous_response_id")
		delete(additionalProperties, "prompt_cache_key")
		delete(additionalProperties, "reasoning")
		delete(additionalProperties, "search_parameters")
		delete(additionalProperties, "service_tier")
		delete(additionalProperties, "store")
		delete(additionalProperties, "stream")
		delete(additionalProperties, "temperature")
		delete(additionalProperties, "text")
		delete(additionalProperties, "tool_choice")
		delete(additionalProperties, "tools")
		delete(additionalProperties, "top_k")
		delete(additionalProperties, "top_logprobs")
		delete(additionalProperties, "top_p")
		delete(additionalProperties, "truncation")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelRequest struct {
	value *ModelRequest
	isSet bool
}

func (v NullableModelRequest) Get() *ModelRequest {
	return v.value
}

func (v *NullableModelRequest) Set(val *ModelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelRequest(val *ModelRequest) *NullableModelRequest {
	return &NullableModelRequest{value: val, isSet: true}
}

func (v NullableModelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
