/*
xAI's REST API

REST API for xAI compatible with other providers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xai

import (
	"encoding/json"
)

// checks if the ModelResponseConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelResponseConfiguration{}

// ModelResponseConfiguration struct for ModelResponseConfiguration
type ModelResponseConfiguration struct {
	// An object specifying the format that the model must output. Specify `{ \"type\": \"json_object\" }` for JSON output, or `{ \"type\": \"json_schema\", \"json_schema\": {...} }` for structured outputs. If `{ \\\"type\\\": \\\"text\\\" }`, the model will return a text response.
	Format NullableModelResponseFormat `json:"format,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelResponseConfiguration ModelResponseConfiguration

// NewModelResponseConfiguration instantiates a new ModelResponseConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelResponseConfiguration() *ModelResponseConfiguration {
	this := ModelResponseConfiguration{}
	return &this
}

// NewModelResponseConfigurationWithDefaults instantiates a new ModelResponseConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelResponseConfigurationWithDefaults() *ModelResponseConfiguration {
	this := ModelResponseConfiguration{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelResponseConfiguration) GetFormat() ModelResponseFormat {
	if o == nil || IsNil(o.Format.Get()) {
		var ret ModelResponseFormat
		return ret
	}
	return *o.Format.Get()
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelResponseConfiguration) GetFormatOk() (*ModelResponseFormat, bool) {
	if o == nil {
		return nil, false
	}
	return o.Format.Get(), o.Format.IsSet()
}

// HasFormat returns a boolean if a field has been set.
func (o *ModelResponseConfiguration) HasFormat() bool {
	if o != nil && o.Format.IsSet() {
		return true
	}

	return false
}

// SetFormat gets a reference to the given NullableModelResponseFormat and assigns it to the Format field.
func (o *ModelResponseConfiguration) SetFormat(v ModelResponseFormat) {
	o.Format.Set(&v)
}
// SetFormatNil sets the value for Format to be an explicit nil
func (o *ModelResponseConfiguration) SetFormatNil() {
	o.Format.Set(nil)
}

// UnsetFormat ensures that no value is present for Format, not even an explicit nil
func (o *ModelResponseConfiguration) UnsetFormat() {
	o.Format.Unset()
}

func (o ModelResponseConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelResponseConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Format.IsSet() {
		toSerialize["format"] = o.Format.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelResponseConfiguration) UnmarshalJSON(data []byte) (err error) {
	varModelResponseConfiguration := _ModelResponseConfiguration{}

	err = json.Unmarshal(data, &varModelResponseConfiguration)

	if err != nil {
		return err
	}

	*o = ModelResponseConfiguration(varModelResponseConfiguration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "format")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelResponseConfiguration struct {
	value *ModelResponseConfiguration
	isSet bool
}

func (v NullableModelResponseConfiguration) Get() *ModelResponseConfiguration {
	return v.value
}

func (v *NullableModelResponseConfiguration) Set(val *ModelResponseConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableModelResponseConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableModelResponseConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelResponseConfiguration(val *ModelResponseConfiguration) *NullableModelResponseConfiguration {
	return &NullableModelResponseConfiguration{value: val, isSet: true}
}

func (v NullableModelResponseConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelResponseConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
