/*
xAI's REST API

REST API for xAI compatible with other providers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xai

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelInputContentItemOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelInputContentItemOneOf2{}

// ModelInputContentItemOneOf2 Image input. Note: Storing and fetching images is not fully supported at the moment.
type ModelInputContentItemOneOf2 struct {
	// Only included for compatibility.
	FileId NullableString `json:"file_id,omitempty"`
	// A public URL of image prompt, only available for vision models.
	ImageUrl string `json:"image_url"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _ModelInputContentItemOneOf2 ModelInputContentItemOneOf2

// NewModelInputContentItemOneOf2 instantiates a new ModelInputContentItemOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelInputContentItemOneOf2(imageUrl string, type_ string) *ModelInputContentItemOneOf2 {
	this := ModelInputContentItemOneOf2{}
	this.ImageUrl = imageUrl
	this.Type = type_
	return &this
}

// NewModelInputContentItemOneOf2WithDefaults instantiates a new ModelInputContentItemOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelInputContentItemOneOf2WithDefaults() *ModelInputContentItemOneOf2 {
	this := ModelInputContentItemOneOf2{}
	return &this
}

// GetFileId returns the FileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelInputContentItemOneOf2) GetFileId() string {
	if o == nil || IsNil(o.FileId.Get()) {
		var ret string
		return ret
	}
	return *o.FileId.Get()
}

// GetFileIdOk returns a tuple with the FileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelInputContentItemOneOf2) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileId.Get(), o.FileId.IsSet()
}

// HasFileId returns a boolean if a field has been set.
func (o *ModelInputContentItemOneOf2) HasFileId() bool {
	if o != nil && o.FileId.IsSet() {
		return true
	}

	return false
}

// SetFileId gets a reference to the given NullableString and assigns it to the FileId field.
func (o *ModelInputContentItemOneOf2) SetFileId(v string) {
	o.FileId.Set(&v)
}
// SetFileIdNil sets the value for FileId to be an explicit nil
func (o *ModelInputContentItemOneOf2) SetFileIdNil() {
	o.FileId.Set(nil)
}

// UnsetFileId ensures that no value is present for FileId, not even an explicit nil
func (o *ModelInputContentItemOneOf2) UnsetFileId() {
	o.FileId.Unset()
}

// GetImageUrl returns the ImageUrl field value
func (o *ModelInputContentItemOneOf2) GetImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *ModelInputContentItemOneOf2) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *ModelInputContentItemOneOf2) SetImageUrl(v string) {
	o.ImageUrl = v
}

// GetType returns the Type field value
func (o *ModelInputContentItemOneOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ModelInputContentItemOneOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ModelInputContentItemOneOf2) SetType(v string) {
	o.Type = v
}

func (o ModelInputContentItemOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelInputContentItemOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FileId.IsSet() {
		toSerialize["file_id"] = o.FileId.Get()
	}
	toSerialize["image_url"] = o.ImageUrl
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelInputContentItemOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image_url",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelInputContentItemOneOf2 := _ModelInputContentItemOneOf2{}

	err = json.Unmarshal(data, &varModelInputContentItemOneOf2)

	if err != nil {
		return err
	}

	*o = ModelInputContentItemOneOf2(varModelInputContentItemOneOf2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "file_id")
		delete(additionalProperties, "image_url")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelInputContentItemOneOf2 struct {
	value *ModelInputContentItemOneOf2
	isSet bool
}

func (v NullableModelInputContentItemOneOf2) Get() *ModelInputContentItemOneOf2 {
	return v.value
}

func (v *NullableModelInputContentItemOneOf2) Set(val *ModelInputContentItemOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableModelInputContentItemOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableModelInputContentItemOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelInputContentItemOneOf2(val *ModelInputContentItemOneOf2) *NullableModelInputContentItemOneOf2 {
	return &NullableModelInputContentItemOneOf2{value: val, isSet: true}
}

func (v NullableModelInputContentItemOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelInputContentItemOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
