/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)


type BetaObservabilityTracesAPI interface {

	/*
	GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGet Get span by id

	Get span by id

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param traceId
	@param spanId
	@return ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest
	*/
	GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGet(ctx context.Context, traceId string, spanId string) ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest

	// GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetExecute executes the request
	//  @return GetSpan
	GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetExecute(r ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest) (*GetSpan, *http.Response, error)

	/*
	GetTraceByIdV1ObservabilityTracesTraceIdGet Get trace by id

	Get trace by id

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param traceId
	@return ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest
	*/
	GetTraceByIdV1ObservabilityTracesTraceIdGet(ctx context.Context, traceId string) ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest

	// GetTraceByIdV1ObservabilityTracesTraceIdGetExecute executes the request
	//  @return GetTrace
	GetTraceByIdV1ObservabilityTracesTraceIdGetExecute(r ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest) (*GetTrace, *http.Response, error)

	/*
	GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGet Get options for a trace field

	Get options for a trace field

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param fieldName
	@return ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest
	*/
	GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGet(ctx context.Context, fieldName string) ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest

	// GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetExecute executes the request
	//  @return GetTraceFieldOptions
	GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetExecute(r ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest) (*GetTraceFieldOptions, *http.Response, error)

	/*
	GetTraceFieldsV1ObservabilityTracesFieldsGet Get trace field definitions

	Get trace field definitions

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest
	*/
	GetTraceFieldsV1ObservabilityTracesFieldsGet(ctx context.Context) ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest

	// GetTraceFieldsV1ObservabilityTracesFieldsGetExecute executes the request
	//  @return GetTraceFields
	GetTraceFieldsV1ObservabilityTracesFieldsGetExecute(r ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest) (*GetTraceFields, *http.Response, error)

	/*
	GetTraceSpansV1ObservabilityTracesTraceIdSpansGet Get trace spans

	Get trace spans

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param traceId
	@return ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest
	*/
	GetTraceSpansV1ObservabilityTracesTraceIdSpansGet(ctx context.Context, traceId string) ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest

	// GetTraceSpansV1ObservabilityTracesTraceIdSpansGetExecute executes the request
	//  @return GetSpans
	GetTraceSpansV1ObservabilityTracesTraceIdSpansGetExecute(r ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest) (*GetSpans, *http.Response, error)

	/*
	SearchTracesV1ObservabilityTracesSearchPost Search traces

	Search traces

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiSearchTracesV1ObservabilityTracesSearchPostRequest
	*/
	SearchTracesV1ObservabilityTracesSearchPost(ctx context.Context) ApiSearchTracesV1ObservabilityTracesSearchPostRequest

	// SearchTracesV1ObservabilityTracesSearchPostExecute executes the request
	//  @return GetTraces
	SearchTracesV1ObservabilityTracesSearchPostExecute(r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) (*GetTraces, *http.Response, error)
}

// BetaObservabilityTracesAPIService BetaObservabilityTracesAPI service
type BetaObservabilityTracesAPIService service

type ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest struct {
	ctx context.Context
	ApiService BetaObservabilityTracesAPI
	traceId string
	spanId string
	from *time.Time
	to *time.Time
}

func (r ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest) From(from time.Time) ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest {
	r.from = &from
	return r
}

func (r ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest) To(to time.Time) ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest {
	r.to = &to
	return r
}

func (r ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest) Execute() (*GetSpan, *http.Response, error) {
	return r.ApiService.GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetExecute(r)
}

/*
GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGet Get span by id

Get span by id

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param traceId
 @param spanId
 @return ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest
*/
func (a *BetaObservabilityTracesAPIService) GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGet(ctx context.Context, traceId string, spanId string) ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest {
	return ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest{
		ApiService: a,
		ctx: ctx,
		traceId: traceId,
		spanId: spanId,
	}
}

// Execute executes the request
//  @return GetSpan
func (a *BetaObservabilityTracesAPIService) GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetExecute(r ApiGetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGetRequest) (*GetSpan, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetSpan
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityTracesAPIService.GetSpanByIdV1ObservabilityTracesTraceIdSpansSpanIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/traces/{trace_id}/spans/{span_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"trace_id"+"}", url.PathEscape(parameterValueToString(r.traceId, "traceId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"span_id"+"}", url.PathEscape(parameterValueToString(r.spanId, "spanId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest struct {
	ctx context.Context
	ApiService BetaObservabilityTracesAPI
	traceId string
}

func (r ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest) Execute() (*GetTrace, *http.Response, error) {
	return r.ApiService.GetTraceByIdV1ObservabilityTracesTraceIdGetExecute(r)
}

/*
GetTraceByIdV1ObservabilityTracesTraceIdGet Get trace by id

Get trace by id

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param traceId
 @return ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest
*/
func (a *BetaObservabilityTracesAPIService) GetTraceByIdV1ObservabilityTracesTraceIdGet(ctx context.Context, traceId string) ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest {
	return ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest{
		ApiService: a,
		ctx: ctx,
		traceId: traceId,
	}
}

// Execute executes the request
//  @return GetTrace
func (a *BetaObservabilityTracesAPIService) GetTraceByIdV1ObservabilityTracesTraceIdGetExecute(r ApiGetTraceByIdV1ObservabilityTracesTraceIdGetRequest) (*GetTrace, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetTrace
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityTracesAPIService.GetTraceByIdV1ObservabilityTracesTraceIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/traces/{trace_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"trace_id"+"}", url.PathEscape(parameterValueToString(r.traceId, "traceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest struct {
	ctx context.Context
	ApiService BetaObservabilityTracesAPI
	fieldName string
	from *time.Time
	to *time.Time
}

func (r ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest) From(from time.Time) ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest {
	r.from = &from
	return r
}

func (r ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest) To(to time.Time) ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest {
	r.to = &to
	return r
}

func (r ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest) Execute() (*GetTraceFieldOptions, *http.Response, error) {
	return r.ApiService.GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetExecute(r)
}

/*
GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGet Get options for a trace field

Get options for a trace field

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fieldName
 @return ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest
*/
func (a *BetaObservabilityTracesAPIService) GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGet(ctx context.Context, fieldName string) ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest {
	return ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest{
		ApiService: a,
		ctx: ctx,
		fieldName: fieldName,
	}
}

// Execute executes the request
//  @return GetTraceFieldOptions
func (a *BetaObservabilityTracesAPIService) GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetExecute(r ApiGetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGetRequest) (*GetTraceFieldOptions, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetTraceFieldOptions
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityTracesAPIService.GetTraceFieldOptionsV1ObservabilityTracesFieldsFieldNameOptionsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/traces/fields/{field_name}/options"
	localVarPath = strings.Replace(localVarPath, "{"+"field_name"+"}", url.PathEscape(parameterValueToString(r.fieldName, "fieldName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest struct {
	ctx context.Context
	ApiService BetaObservabilityTracesAPI
}

func (r ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest) Execute() (*GetTraceFields, *http.Response, error) {
	return r.ApiService.GetTraceFieldsV1ObservabilityTracesFieldsGetExecute(r)
}

/*
GetTraceFieldsV1ObservabilityTracesFieldsGet Get trace field definitions

Get trace field definitions

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest
*/
func (a *BetaObservabilityTracesAPIService) GetTraceFieldsV1ObservabilityTracesFieldsGet(ctx context.Context) ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest {
	return ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetTraceFields
func (a *BetaObservabilityTracesAPIService) GetTraceFieldsV1ObservabilityTracesFieldsGetExecute(r ApiGetTraceFieldsV1ObservabilityTracesFieldsGetRequest) (*GetTraceFields, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetTraceFields
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityTracesAPIService.GetTraceFieldsV1ObservabilityTracesFieldsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/traces/fields"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest struct {
	ctx context.Context
	ApiService BetaObservabilityTracesAPI
	traceId string
	from *time.Time
	to *time.Time
	pageSize *int32
	cursor *string
}

func (r ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest) From(from time.Time) ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest {
	r.from = &from
	return r
}

func (r ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest) To(to time.Time) ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest {
	r.to = &to
	return r
}

func (r ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest) PageSize(pageSize int32) ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest) Cursor(cursor string) ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest {
	r.cursor = &cursor
	return r
}

func (r ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest) Execute() (*GetSpans, *http.Response, error) {
	return r.ApiService.GetTraceSpansV1ObservabilityTracesTraceIdSpansGetExecute(r)
}

/*
GetTraceSpansV1ObservabilityTracesTraceIdSpansGet Get trace spans

Get trace spans

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param traceId
 @return ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest
*/
func (a *BetaObservabilityTracesAPIService) GetTraceSpansV1ObservabilityTracesTraceIdSpansGet(ctx context.Context, traceId string) ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest {
	return ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest{
		ApiService: a,
		ctx: ctx,
		traceId: traceId,
	}
}

// Execute executes the request
//  @return GetSpans
func (a *BetaObservabilityTracesAPIService) GetTraceSpansV1ObservabilityTracesTraceIdSpansGetExecute(r ApiGetTraceSpansV1ObservabilityTracesTraceIdSpansGetRequest) (*GetSpans, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetSpans
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityTracesAPIService.GetTraceSpansV1ObservabilityTracesTraceIdSpansGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/traces/{trace_id}/spans"
	localVarPath = strings.Replace(localVarPath, "{"+"trace_id"+"}", url.PathEscape(parameterValueToString(r.traceId, "traceId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 50
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiSearchTracesV1ObservabilityTracesSearchPostRequest struct {
	ctx context.Context
	ApiService BetaObservabilityTracesAPI
	tracesRequest *TracesRequest
	from *time.Time
	to *time.Time
	pageSize *int32
	cursor *string
}

func (r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) TracesRequest(tracesRequest TracesRequest) ApiSearchTracesV1ObservabilityTracesSearchPostRequest {
	r.tracesRequest = &tracesRequest
	return r
}

func (r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) From(from time.Time) ApiSearchTracesV1ObservabilityTracesSearchPostRequest {
	r.from = &from
	return r
}

func (r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) To(to time.Time) ApiSearchTracesV1ObservabilityTracesSearchPostRequest {
	r.to = &to
	return r
}

func (r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) PageSize(pageSize int32) ApiSearchTracesV1ObservabilityTracesSearchPostRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) Cursor(cursor string) ApiSearchTracesV1ObservabilityTracesSearchPostRequest {
	r.cursor = &cursor
	return r
}

func (r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) Execute() (*GetTraces, *http.Response, error) {
	return r.ApiService.SearchTracesV1ObservabilityTracesSearchPostExecute(r)
}

/*
SearchTracesV1ObservabilityTracesSearchPost Search traces

Search traces

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiSearchTracesV1ObservabilityTracesSearchPostRequest
*/
func (a *BetaObservabilityTracesAPIService) SearchTracesV1ObservabilityTracesSearchPost(ctx context.Context) ApiSearchTracesV1ObservabilityTracesSearchPostRequest {
	return ApiSearchTracesV1ObservabilityTracesSearchPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetTraces
func (a *BetaObservabilityTracesAPIService) SearchTracesV1ObservabilityTracesSearchPostExecute(r ApiSearchTracesV1ObservabilityTracesSearchPostRequest) (*GetTraces, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetTraces
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityTracesAPIService.SearchTracesV1ObservabilityTracesSearchPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/traces/search"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tracesRequest == nil {
		return localVarReturnValue, nil, reportError("tracesRequest is required and must be specified")
	}

	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 50
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.tracesRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
