/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


type WorkflowsAPI interface {

	/*
	ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePut Archive Workflow

	Archive Workflow

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param workflowIdentifier
	@return ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest
	*/
	ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePut(ctx context.Context, workflowIdentifier string) ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest

	// ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutExecute executes the request
	//  @return WorkflowArchiveResponse
	ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutExecute(r ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest) (*WorkflowArchiveResponse, *http.Response, error)

	/*
	BulkArchiveWorkflowsV1WorkflowsArchivePut Bulk Archive Workflows

	Bulk Archive Workflows

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest
	*/
	BulkArchiveWorkflowsV1WorkflowsArchivePut(ctx context.Context) ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest

	// BulkArchiveWorkflowsV1WorkflowsArchivePutExecute executes the request
	//  @return WorkflowBulkArchiveResponse
	BulkArchiveWorkflowsV1WorkflowsArchivePutExecute(r ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest) (*WorkflowBulkArchiveResponse, *http.Response, error)

	/*
	BulkUnarchiveWorkflowsV1WorkflowsUnarchivePut Bulk Unarchive Workflows

	Bulk Unarchive Workflows

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest
	*/
	BulkUnarchiveWorkflowsV1WorkflowsUnarchivePut(ctx context.Context) ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest

	// BulkUnarchiveWorkflowsV1WorkflowsUnarchivePutExecute executes the request
	//  @return WorkflowBulkUnarchiveResponse
	BulkUnarchiveWorkflowsV1WorkflowsUnarchivePutExecute(r ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest) (*WorkflowBulkUnarchiveResponse, *http.Response, error)

	/*
	ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost Execute Workflow Registration

	Execute Workflow Registration

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param workflowRegistrationId
	@return ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest

	Deprecated
	*/
	ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost(ctx context.Context, workflowRegistrationId string) ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest

	// ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostExecute executes the request
	//  @return ResponseExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost
	// Deprecated
	ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostExecute(r ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest) (*ResponseExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost, *http.Response, error)

	/*
	ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost Execute Workflow

	Execute Workflow

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param workflowIdentifier
	@return ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest
	*/
	ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost(ctx context.Context, workflowIdentifier string) ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest

	// ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostExecute executes the request
	//  @return ResponseExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost
	ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostExecute(r ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest) (*ResponseExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost, *http.Response, error)

	/*
	GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGet Get Workflow Registration

	Get Workflow Registration

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param workflowRegistrationId
	@return ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest
	*/
	GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGet(ctx context.Context, workflowRegistrationId string) ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest

	// GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetExecute executes the request
	//  @return WorkflowRegistrationGetResponse
	GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetExecute(r ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest) (*WorkflowRegistrationGetResponse, *http.Response, error)

	/*
	GetWorkflowRegistrationsV1WorkflowsRegistrationsGet Get Workflow Registrations

	Get Workflow Registrations

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest
	*/
	GetWorkflowRegistrationsV1WorkflowsRegistrationsGet(ctx context.Context) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest

	// GetWorkflowRegistrationsV1WorkflowsRegistrationsGetExecute executes the request
	//  @return WorkflowRegistrationListResponse
	GetWorkflowRegistrationsV1WorkflowsRegistrationsGetExecute(r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) (*WorkflowRegistrationListResponse, *http.Response, error)

	/*
	GetWorkflowV1WorkflowsWorkflowIdentifierGet Get Workflow

	Get Workflow

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param workflowIdentifier
	@return ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest
	*/
	GetWorkflowV1WorkflowsWorkflowIdentifierGet(ctx context.Context, workflowIdentifier string) ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest

	// GetWorkflowV1WorkflowsWorkflowIdentifierGetExecute executes the request
	//  @return WorkflowGetResponse
	GetWorkflowV1WorkflowsWorkflowIdentifierGetExecute(r ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest) (*WorkflowGetResponse, *http.Response, error)

	/*
	GetWorkflowsV1WorkflowsGet Get Workflows

	Get Workflows

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetWorkflowsV1WorkflowsGetRequest
	*/
	GetWorkflowsV1WorkflowsGet(ctx context.Context) ApiGetWorkflowsV1WorkflowsGetRequest

	// GetWorkflowsV1WorkflowsGetExecute executes the request
	//  @return WorkflowListResponse
	GetWorkflowsV1WorkflowsGetExecute(r ApiGetWorkflowsV1WorkflowsGetRequest) (*WorkflowListResponse, *http.Response, error)

	/*
	UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePut Unarchive Workflow

	Unarchive Workflow

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param workflowIdentifier
	@return ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest
	*/
	UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePut(ctx context.Context, workflowIdentifier string) ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest

	// UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutExecute executes the request
	//  @return WorkflowUnarchiveResponse
	UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutExecute(r ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest) (*WorkflowUnarchiveResponse, *http.Response, error)

	/*
	UpdateWorkflowV1WorkflowsWorkflowIdentifierPut Update Workflow

	Update Workflow

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param workflowIdentifier
	@return ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest
	*/
	UpdateWorkflowV1WorkflowsWorkflowIdentifierPut(ctx context.Context, workflowIdentifier string) ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest

	// UpdateWorkflowV1WorkflowsWorkflowIdentifierPutExecute executes the request
	//  @return WorkflowUpdateResponse
	UpdateWorkflowV1WorkflowsWorkflowIdentifierPutExecute(r ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest) (*WorkflowUpdateResponse, *http.Response, error)
}

// WorkflowsAPIService WorkflowsAPI service
type WorkflowsAPIService service

type ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowIdentifier string
}

func (r ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest) Execute() (*WorkflowArchiveResponse, *http.Response, error) {
	return r.ApiService.ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutExecute(r)
}

/*
ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePut Archive Workflow

Archive Workflow

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param workflowIdentifier
 @return ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest
*/
func (a *WorkflowsAPIService) ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePut(ctx context.Context, workflowIdentifier string) ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest {
	return ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest{
		ApiService: a,
		ctx: ctx,
		workflowIdentifier: workflowIdentifier,
	}
}

// Execute executes the request
//  @return WorkflowArchiveResponse
func (a *WorkflowsAPIService) ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutExecute(r ApiArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePutRequest) (*WorkflowArchiveResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowArchiveResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.ArchiveWorkflowV1WorkflowsWorkflowIdentifierArchivePut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/{workflow_identifier}/archive"
	localVarPath = strings.Replace(localVarPath, "{"+"workflow_identifier"+"}", url.PathEscape(parameterValueToString(r.workflowIdentifier, "workflowIdentifier")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowBulkArchiveRequest *WorkflowBulkArchiveRequest
}

func (r ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest) WorkflowBulkArchiveRequest(workflowBulkArchiveRequest WorkflowBulkArchiveRequest) ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest {
	r.workflowBulkArchiveRequest = &workflowBulkArchiveRequest
	return r
}

func (r ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest) Execute() (*WorkflowBulkArchiveResponse, *http.Response, error) {
	return r.ApiService.BulkArchiveWorkflowsV1WorkflowsArchivePutExecute(r)
}

/*
BulkArchiveWorkflowsV1WorkflowsArchivePut Bulk Archive Workflows

Bulk Archive Workflows

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest
*/
func (a *WorkflowsAPIService) BulkArchiveWorkflowsV1WorkflowsArchivePut(ctx context.Context) ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest {
	return ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WorkflowBulkArchiveResponse
func (a *WorkflowsAPIService) BulkArchiveWorkflowsV1WorkflowsArchivePutExecute(r ApiBulkArchiveWorkflowsV1WorkflowsArchivePutRequest) (*WorkflowBulkArchiveResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowBulkArchiveResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.BulkArchiveWorkflowsV1WorkflowsArchivePut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/archive"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.workflowBulkArchiveRequest == nil {
		return localVarReturnValue, nil, reportError("workflowBulkArchiveRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.workflowBulkArchiveRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowBulkUnarchiveRequest *WorkflowBulkUnarchiveRequest
}

func (r ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest) WorkflowBulkUnarchiveRequest(workflowBulkUnarchiveRequest WorkflowBulkUnarchiveRequest) ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest {
	r.workflowBulkUnarchiveRequest = &workflowBulkUnarchiveRequest
	return r
}

func (r ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest) Execute() (*WorkflowBulkUnarchiveResponse, *http.Response, error) {
	return r.ApiService.BulkUnarchiveWorkflowsV1WorkflowsUnarchivePutExecute(r)
}

/*
BulkUnarchiveWorkflowsV1WorkflowsUnarchivePut Bulk Unarchive Workflows

Bulk Unarchive Workflows

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest
*/
func (a *WorkflowsAPIService) BulkUnarchiveWorkflowsV1WorkflowsUnarchivePut(ctx context.Context) ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest {
	return ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WorkflowBulkUnarchiveResponse
func (a *WorkflowsAPIService) BulkUnarchiveWorkflowsV1WorkflowsUnarchivePutExecute(r ApiBulkUnarchiveWorkflowsV1WorkflowsUnarchivePutRequest) (*WorkflowBulkUnarchiveResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowBulkUnarchiveResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.BulkUnarchiveWorkflowsV1WorkflowsUnarchivePut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/unarchive"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.workflowBulkUnarchiveRequest == nil {
		return localVarReturnValue, nil, reportError("workflowBulkUnarchiveRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.workflowBulkUnarchiveRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowRegistrationId string
	workflowExecutionRequest *WorkflowExecutionRequest
}

func (r ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest) WorkflowExecutionRequest(workflowExecutionRequest WorkflowExecutionRequest) ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest {
	r.workflowExecutionRequest = &workflowExecutionRequest
	return r
}

func (r ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest) Execute() (*ResponseExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost, *http.Response, error) {
	return r.ApiService.ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostExecute(r)
}

/*
ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost Execute Workflow Registration

Execute Workflow Registration

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param workflowRegistrationId
 @return ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest

Deprecated
*/
func (a *WorkflowsAPIService) ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost(ctx context.Context, workflowRegistrationId string) ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest {
	return ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest{
		ApiService: a,
		ctx: ctx,
		workflowRegistrationId: workflowRegistrationId,
	}
}

// Execute executes the request
//  @return ResponseExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost
// Deprecated
func (a *WorkflowsAPIService) ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostExecute(r ApiExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePostRequest) (*ResponseExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResponseExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.ExecuteWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdExecutePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/registrations/{workflow_registration_id}/execute"
	localVarPath = strings.Replace(localVarPath, "{"+"workflow_registration_id"+"}", url.PathEscape(parameterValueToString(r.workflowRegistrationId, "workflowRegistrationId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.workflowExecutionRequest == nil {
		return localVarReturnValue, nil, reportError("workflowExecutionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.workflowExecutionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowIdentifier string
	workflowExecutionRequest *WorkflowExecutionRequest
}

func (r ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest) WorkflowExecutionRequest(workflowExecutionRequest WorkflowExecutionRequest) ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest {
	r.workflowExecutionRequest = &workflowExecutionRequest
	return r
}

func (r ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest) Execute() (*ResponseExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost, *http.Response, error) {
	return r.ApiService.ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostExecute(r)
}

/*
ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost Execute Workflow

Execute Workflow

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param workflowIdentifier
 @return ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest
*/
func (a *WorkflowsAPIService) ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost(ctx context.Context, workflowIdentifier string) ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest {
	return ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest{
		ApiService: a,
		ctx: ctx,
		workflowIdentifier: workflowIdentifier,
	}
}

// Execute executes the request
//  @return ResponseExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost
func (a *WorkflowsAPIService) ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostExecute(r ApiExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePostRequest) (*ResponseExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResponseExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.ExecuteWorkflowV1WorkflowsWorkflowIdentifierExecutePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/{workflow_identifier}/execute"
	localVarPath = strings.Replace(localVarPath, "{"+"workflow_identifier"+"}", url.PathEscape(parameterValueToString(r.workflowIdentifier, "workflowIdentifier")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.workflowExecutionRequest == nil {
		return localVarReturnValue, nil, reportError("workflowExecutionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.workflowExecutionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowRegistrationId string
	withWorkflow *bool
	includeShared *bool
}

// Whether to include the workflow definition
func (r ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest) WithWorkflow(withWorkflow bool) ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest {
	r.withWorkflow = &withWorkflow
	return r
}

// Whether to include shared workflow versions
func (r ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest) IncludeShared(includeShared bool) ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest {
	r.includeShared = &includeShared
	return r
}

func (r ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest) Execute() (*WorkflowRegistrationGetResponse, *http.Response, error) {
	return r.ApiService.GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetExecute(r)
}

/*
GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGet Get Workflow Registration

Get Workflow Registration

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param workflowRegistrationId
 @return ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest
*/
func (a *WorkflowsAPIService) GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGet(ctx context.Context, workflowRegistrationId string) ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest {
	return ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest{
		ApiService: a,
		ctx: ctx,
		workflowRegistrationId: workflowRegistrationId,
	}
}

// Execute executes the request
//  @return WorkflowRegistrationGetResponse
func (a *WorkflowsAPIService) GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetExecute(r ApiGetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGetRequest) (*WorkflowRegistrationGetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowRegistrationGetResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.GetWorkflowRegistrationV1WorkflowsRegistrationsWorkflowRegistrationIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/registrations/{workflow_registration_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"workflow_registration_id"+"}", url.PathEscape(parameterValueToString(r.workflowRegistrationId, "workflowRegistrationId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.withWorkflow != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "with_workflow", r.withWorkflow, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "with_workflow", defaultValue, "form", "")
		r.withWorkflow = &defaultValue
	}
	if r.includeShared != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_shared", r.includeShared, "form", "")
	} else {
		var defaultValue bool = true
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_shared", defaultValue, "form", "")
		r.includeShared = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowId *string
	taskQueue *string
	activeOnly *bool
	includeShared *bool
	workflowSearch *string
	archived *bool
	withWorkflow *bool
	availableInChatAssistant *bool
	limit *int32
	cursor *string
}

// The workflow ID to filter by
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) WorkflowId(workflowId string) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.workflowId = &workflowId
	return r
}

// The task queue to filter by
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) TaskQueue(taskQueue string) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.taskQueue = &taskQueue
	return r
}

// Whether to only return active workflows versions
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) ActiveOnly(activeOnly bool) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.activeOnly = &activeOnly
	return r
}

// Whether to include shared workflow versions
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) IncludeShared(includeShared bool) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.includeShared = &includeShared
	return r
}

// The workflow name to filter by
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) WorkflowSearch(workflowSearch string) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.workflowSearch = &workflowSearch
	return r
}

// Filter by archived state. False&#x3D;exclude archived, True&#x3D;only archived, None&#x3D;include all
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) Archived(archived bool) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.archived = &archived
	return r
}

// Whether to include the workflow definition
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) WithWorkflow(withWorkflow bool) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.withWorkflow = &withWorkflow
	return r
}

// Whether to only return workflows available in chat assistant
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) AvailableInChatAssistant(availableInChatAssistant bool) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.availableInChatAssistant = &availableInChatAssistant
	return r
}

// The maximum number of workflows versions to return
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) Limit(limit int32) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.limit = &limit
	return r
}

// The cursor for pagination
func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) Cursor(cursor string) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	r.cursor = &cursor
	return r
}

func (r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) Execute() (*WorkflowRegistrationListResponse, *http.Response, error) {
	return r.ApiService.GetWorkflowRegistrationsV1WorkflowsRegistrationsGetExecute(r)
}

/*
GetWorkflowRegistrationsV1WorkflowsRegistrationsGet Get Workflow Registrations

Get Workflow Registrations

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest
*/
func (a *WorkflowsAPIService) GetWorkflowRegistrationsV1WorkflowsRegistrationsGet(ctx context.Context) ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest {
	return ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WorkflowRegistrationListResponse
func (a *WorkflowsAPIService) GetWorkflowRegistrationsV1WorkflowsRegistrationsGetExecute(r ApiGetWorkflowRegistrationsV1WorkflowsRegistrationsGetRequest) (*WorkflowRegistrationListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowRegistrationListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.GetWorkflowRegistrationsV1WorkflowsRegistrationsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/registrations"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.workflowId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "workflow_id", r.workflowId, "form", "")
	}
	if r.taskQueue != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "task_queue", r.taskQueue, "form", "")
	}
	if r.activeOnly != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "active_only", r.activeOnly, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "active_only", defaultValue, "form", "")
		r.activeOnly = &defaultValue
	}
	if r.includeShared != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_shared", r.includeShared, "form", "")
	} else {
		var defaultValue bool = true
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_shared", defaultValue, "form", "")
		r.includeShared = &defaultValue
	}
	if r.workflowSearch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "workflow_search", r.workflowSearch, "form", "")
	}
	if r.archived != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "archived", r.archived, "form", "")
	}
	if r.withWorkflow != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "with_workflow", r.withWorkflow, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "with_workflow", defaultValue, "form", "")
		r.withWorkflow = &defaultValue
	}
	if r.availableInChatAssistant != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "available_in_chat_assistant", r.availableInChatAssistant, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 50
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
		r.limit = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowIdentifier string
}

func (r ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest) Execute() (*WorkflowGetResponse, *http.Response, error) {
	return r.ApiService.GetWorkflowV1WorkflowsWorkflowIdentifierGetExecute(r)
}

/*
GetWorkflowV1WorkflowsWorkflowIdentifierGet Get Workflow

Get Workflow

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param workflowIdentifier
 @return ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest
*/
func (a *WorkflowsAPIService) GetWorkflowV1WorkflowsWorkflowIdentifierGet(ctx context.Context, workflowIdentifier string) ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest {
	return ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest{
		ApiService: a,
		ctx: ctx,
		workflowIdentifier: workflowIdentifier,
	}
}

// Execute executes the request
//  @return WorkflowGetResponse
func (a *WorkflowsAPIService) GetWorkflowV1WorkflowsWorkflowIdentifierGetExecute(r ApiGetWorkflowV1WorkflowsWorkflowIdentifierGetRequest) (*WorkflowGetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowGetResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.GetWorkflowV1WorkflowsWorkflowIdentifierGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/{workflow_identifier}"
	localVarPath = strings.Replace(localVarPath, "{"+"workflow_identifier"+"}", url.PathEscape(parameterValueToString(r.workflowIdentifier, "workflowIdentifier")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetWorkflowsV1WorkflowsGetRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	status *Status
	includeShared *bool
	availableInChatAssistant *bool
	deploymentName *[]string
	deploymentStatus *string
	archived *bool
	tags *[]string
	sortBy *string
	order *string
	cursor *string
	limit *int32
	activeOnly *bool
	search *string
}

// Filter by workflow status
func (r ApiGetWorkflowsV1WorkflowsGetRequest) Status(status Status) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.status = &status
	return r
}

// Whether to include shared workflows
func (r ApiGetWorkflowsV1WorkflowsGetRequest) IncludeShared(includeShared bool) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.includeShared = &includeShared
	return r
}

// Whether to only return workflows available in chat assistant
func (r ApiGetWorkflowsV1WorkflowsGetRequest) AvailableInChatAssistant(availableInChatAssistant bool) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.availableInChatAssistant = &availableInChatAssistant
	return r
}

// Filter by deployment name(s)
func (r ApiGetWorkflowsV1WorkflowsGetRequest) DeploymentName(deploymentName []string) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.deploymentName = &deploymentName
	return r
}

// Filter by deployment activity. active&#x3D;only active, inactive&#x3D;only inactive, None&#x3D;no filter
func (r ApiGetWorkflowsV1WorkflowsGetRequest) DeploymentStatus(deploymentStatus string) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.deploymentStatus = &deploymentStatus
	return r
}

// Filter by archived state. False&#x3D;exclude archived, True&#x3D;only archived, None&#x3D;include all
func (r ApiGetWorkflowsV1WorkflowsGetRequest) Archived(archived bool) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.archived = &archived
	return r
}

// Filter to workflows tagged with all listed tags (AND).
func (r ApiGetWorkflowsV1WorkflowsGetRequest) Tags(tags []string) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.tags = &tags
	return r
}

// Field to sort by
func (r ApiGetWorkflowsV1WorkflowsGetRequest) SortBy(sortBy string) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.sortBy = &sortBy
	return r
}

// Sort direction
func (r ApiGetWorkflowsV1WorkflowsGetRequest) Order(order string) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.order = &order
	return r
}

// The cursor for pagination
func (r ApiGetWorkflowsV1WorkflowsGetRequest) Cursor(cursor string) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.cursor = &cursor
	return r
}

// The maximum number of workflows to return
func (r ApiGetWorkflowsV1WorkflowsGetRequest) Limit(limit int32) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.limit = &limit
	return r
}

// Deprecated: use deployment_status instead
// Deprecated
func (r ApiGetWorkflowsV1WorkflowsGetRequest) ActiveOnly(activeOnly bool) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.activeOnly = &activeOnly
	return r
}

// Fuzzy search query for workflow name, display name, description, or ID
func (r ApiGetWorkflowsV1WorkflowsGetRequest) Search(search string) ApiGetWorkflowsV1WorkflowsGetRequest {
	r.search = &search
	return r
}

func (r ApiGetWorkflowsV1WorkflowsGetRequest) Execute() (*WorkflowListResponse, *http.Response, error) {
	return r.ApiService.GetWorkflowsV1WorkflowsGetExecute(r)
}

/*
GetWorkflowsV1WorkflowsGet Get Workflows

Get Workflows

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetWorkflowsV1WorkflowsGetRequest
*/
func (a *WorkflowsAPIService) GetWorkflowsV1WorkflowsGet(ctx context.Context) ApiGetWorkflowsV1WorkflowsGetRequest {
	return ApiGetWorkflowsV1WorkflowsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WorkflowListResponse
func (a *WorkflowsAPIService) GetWorkflowsV1WorkflowsGetExecute(r ApiGetWorkflowsV1WorkflowsGetRequest) (*WorkflowListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.GetWorkflowsV1WorkflowsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.status != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "status", r.status, "form", "")
	}
	if r.includeShared != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_shared", r.includeShared, "form", "")
	} else {
		var defaultValue bool = true
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_shared", defaultValue, "form", "")
		r.includeShared = &defaultValue
	}
	if r.availableInChatAssistant != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "available_in_chat_assistant", r.availableInChatAssistant, "form", "")
	}
	if r.deploymentName != nil {
		t := *r.deploymentName
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "deployment_name", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "deployment_name", t, "form", "multi")
		}
	}
	if r.deploymentStatus != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "deployment_status", r.deploymentStatus, "form", "")
	}
	if r.archived != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "archived", r.archived, "form", "")
	}
	if r.tags != nil {
		t := *r.tags
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "tags", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "tags", t, "form", "multi")
		}
	}
	if r.sortBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort_by", r.sortBy, "form", "")
	}
	if r.order != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "order", r.order, "form", "")
	} else {
		var defaultValue string = "asc"
		parameterAddToHeaderOrQuery(localVarQueryParams, "order", defaultValue, "form", "")
		r.order = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 50
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
		r.limit = &defaultValue
	}
	if r.activeOnly != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "active_only", r.activeOnly, "form", "")
	} else {
		var defaultValue bool = false
		parameterAddToHeaderOrQuery(localVarQueryParams, "active_only", defaultValue, "form", "")
		r.activeOnly = &defaultValue
	}
	if r.search != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search", r.search, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowIdentifier string
}

func (r ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest) Execute() (*WorkflowUnarchiveResponse, *http.Response, error) {
	return r.ApiService.UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutExecute(r)
}

/*
UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePut Unarchive Workflow

Unarchive Workflow

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param workflowIdentifier
 @return ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest
*/
func (a *WorkflowsAPIService) UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePut(ctx context.Context, workflowIdentifier string) ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest {
	return ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest{
		ApiService: a,
		ctx: ctx,
		workflowIdentifier: workflowIdentifier,
	}
}

// Execute executes the request
//  @return WorkflowUnarchiveResponse
func (a *WorkflowsAPIService) UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutExecute(r ApiUnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePutRequest) (*WorkflowUnarchiveResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowUnarchiveResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.UnarchiveWorkflowV1WorkflowsWorkflowIdentifierUnarchivePut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/{workflow_identifier}/unarchive"
	localVarPath = strings.Replace(localVarPath, "{"+"workflow_identifier"+"}", url.PathEscape(parameterValueToString(r.workflowIdentifier, "workflowIdentifier")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest struct {
	ctx context.Context
	ApiService WorkflowsAPI
	workflowIdentifier string
	workflowUpdateRequest *WorkflowUpdateRequest
}

func (r ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest) WorkflowUpdateRequest(workflowUpdateRequest WorkflowUpdateRequest) ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest {
	r.workflowUpdateRequest = &workflowUpdateRequest
	return r
}

func (r ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest) Execute() (*WorkflowUpdateResponse, *http.Response, error) {
	return r.ApiService.UpdateWorkflowV1WorkflowsWorkflowIdentifierPutExecute(r)
}

/*
UpdateWorkflowV1WorkflowsWorkflowIdentifierPut Update Workflow

Update Workflow

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param workflowIdentifier
 @return ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest
*/
func (a *WorkflowsAPIService) UpdateWorkflowV1WorkflowsWorkflowIdentifierPut(ctx context.Context, workflowIdentifier string) ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest {
	return ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest{
		ApiService: a,
		ctx: ctx,
		workflowIdentifier: workflowIdentifier,
	}
}

// Execute executes the request
//  @return WorkflowUpdateResponse
func (a *WorkflowsAPIService) UpdateWorkflowV1WorkflowsWorkflowIdentifierPutExecute(r ApiUpdateWorkflowV1WorkflowsWorkflowIdentifierPutRequest) (*WorkflowUpdateResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkflowUpdateResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WorkflowsAPIService.UpdateWorkflowV1WorkflowsWorkflowIdentifierPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/workflows/{workflow_identifier}"
	localVarPath = strings.Replace(localVarPath, "{"+"workflow_identifier"+"}", url.PathEscape(parameterValueToString(r.workflowIdentifier, "workflowIdentifier")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.workflowUpdateRequest == nil {
		return localVarReturnValue, nil, reportError("workflowUpdateRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.workflowUpdateRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
