/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type BetaAdminBillingAPI interface {

	/*
	UsersApiAdminRateLimitsGetRateLimits Get Rate Limits

	Get Rate Limits

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiUsersApiAdminRateLimitsGetRateLimitsRequest
	*/
	UsersApiAdminRateLimitsGetRateLimits(ctx context.Context) ApiUsersApiAdminRateLimitsGetRateLimitsRequest

	// UsersApiAdminRateLimitsGetRateLimitsExecute executes the request
	//  @return RateLimitsOUT
	UsersApiAdminRateLimitsGetRateLimitsExecute(r ApiUsersApiAdminRateLimitsGetRateLimitsRequest) (*RateLimitsOUT, *http.Response, error)

	/*
	UsersApiAdminSpendLimitsGetSpendLimits Get Spend Limits

	Get usage, rate, and job limits for the Organization.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest
	*/
	UsersApiAdminSpendLimitsGetSpendLimits(ctx context.Context) ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest

	// UsersApiAdminSpendLimitsGetSpendLimitsExecute executes the request
	//  @return LimitsOUT
	UsersApiAdminSpendLimitsGetSpendLimitsExecute(r ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest) (*LimitsOUT, *http.Response, error)

	/*
	UsersApiAdminSpendLimitsUpdateSpendLimits Update Spend Limits

	Update the Organization usage limit.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest
	*/
	UsersApiAdminSpendLimitsUpdateSpendLimits(ctx context.Context) ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest

	// UsersApiAdminSpendLimitsUpdateSpendLimitsExecute executes the request
	//  @return LimitsOUT
	UsersApiAdminSpendLimitsUpdateSpendLimitsExecute(r ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest) (*LimitsOUT, *http.Response, error)

	/*
	UsersApiAdminUsageGetUsage Get Usage

	Get usage and cost data for the Organization.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiUsersApiAdminUsageGetUsageRequest
	*/
	UsersApiAdminUsageGetUsage(ctx context.Context) ApiUsersApiAdminUsageGetUsageRequest

	// UsersApiAdminUsageGetUsageExecute executes the request
	//  @return UsageOUTJSON
	UsersApiAdminUsageGetUsageExecute(r ApiUsersApiAdminUsageGetUsageRequest) (*UsageOUTJSON, *http.Response, error)
}

// BetaAdminBillingAPIService BetaAdminBillingAPI service
type BetaAdminBillingAPIService service

type ApiUsersApiAdminRateLimitsGetRateLimitsRequest struct {
	ctx context.Context
	ApiService BetaAdminBillingAPI
}

func (r ApiUsersApiAdminRateLimitsGetRateLimitsRequest) Execute() (*RateLimitsOUT, *http.Response, error) {
	return r.ApiService.UsersApiAdminRateLimitsGetRateLimitsExecute(r)
}

/*
UsersApiAdminRateLimitsGetRateLimits Get Rate Limits

Get Rate Limits

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiUsersApiAdminRateLimitsGetRateLimitsRequest
*/
func (a *BetaAdminBillingAPIService) UsersApiAdminRateLimitsGetRateLimits(ctx context.Context) ApiUsersApiAdminRateLimitsGetRateLimitsRequest {
	return ApiUsersApiAdminRateLimitsGetRateLimitsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return RateLimitsOUT
func (a *BetaAdminBillingAPIService) UsersApiAdminRateLimitsGetRateLimitsExecute(r ApiUsersApiAdminRateLimitsGetRateLimitsRequest) (*RateLimitsOUT, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RateLimitsOUT
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaAdminBillingAPIService.UsersApiAdminRateLimitsGetRateLimits")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/admin/rate-limit"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest struct {
	ctx context.Context
	ApiService BetaAdminBillingAPI
}

func (r ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest) Execute() (*LimitsOUT, *http.Response, error) {
	return r.ApiService.UsersApiAdminSpendLimitsGetSpendLimitsExecute(r)
}

/*
UsersApiAdminSpendLimitsGetSpendLimits Get Spend Limits

Get usage, rate, and job limits for the Organization.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest
*/
func (a *BetaAdminBillingAPIService) UsersApiAdminSpendLimitsGetSpendLimits(ctx context.Context) ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest {
	return ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return LimitsOUT
func (a *BetaAdminBillingAPIService) UsersApiAdminSpendLimitsGetSpendLimitsExecute(r ApiUsersApiAdminSpendLimitsGetSpendLimitsRequest) (*LimitsOUT, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *LimitsOUT
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaAdminBillingAPIService.UsersApiAdminSpendLimitsGetSpendLimits")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/admin/spend-limit"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest struct {
	ctx context.Context
	ApiService BetaAdminBillingAPI
	newUsageLimitIN *NewUsageLimitIN
}

func (r ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest) NewUsageLimitIN(newUsageLimitIN NewUsageLimitIN) ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest {
	r.newUsageLimitIN = &newUsageLimitIN
	return r
}

func (r ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest) Execute() (*LimitsOUT, *http.Response, error) {
	return r.ApiService.UsersApiAdminSpendLimitsUpdateSpendLimitsExecute(r)
}

/*
UsersApiAdminSpendLimitsUpdateSpendLimits Update Spend Limits

Update the Organization usage limit.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest
*/
func (a *BetaAdminBillingAPIService) UsersApiAdminSpendLimitsUpdateSpendLimits(ctx context.Context) ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest {
	return ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return LimitsOUT
func (a *BetaAdminBillingAPIService) UsersApiAdminSpendLimitsUpdateSpendLimitsExecute(r ApiUsersApiAdminSpendLimitsUpdateSpendLimitsRequest) (*LimitsOUT, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *LimitsOUT
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaAdminBillingAPIService.UsersApiAdminSpendLimitsUpdateSpendLimits")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/admin/spend-limit"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.newUsageLimitIN == nil {
		return localVarReturnValue, nil, reportError("newUsageLimitIN is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.newUsageLimitIN
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUsersApiAdminUsageGetUsageRequest struct {
	ctx context.Context
	ApiService BetaAdminBillingAPI
	month *string
	year *string
	workspaceId *string
	apiZone *ApiZone
}

// Month to return usage for.
func (r ApiUsersApiAdminUsageGetUsageRequest) Month(month string) ApiUsersApiAdminUsageGetUsageRequest {
	r.month = &month
	return r
}

// Year to return usage for.
func (r ApiUsersApiAdminUsageGetUsageRequest) Year(year string) ApiUsersApiAdminUsageGetUsageRequest {
	r.year = &year
	return r
}

// Workspace ID to filter results.
func (r ApiUsersApiAdminUsageGetUsageRequest) WorkspaceId(workspaceId string) ApiUsersApiAdminUsageGetUsageRequest {
	r.workspaceId = &workspaceId
	return r
}

// Regional inference zone to filter results.
func (r ApiUsersApiAdminUsageGetUsageRequest) ApiZone(apiZone ApiZone) ApiUsersApiAdminUsageGetUsageRequest {
	r.apiZone = &apiZone
	return r
}

func (r ApiUsersApiAdminUsageGetUsageRequest) Execute() (*UsageOUTJSON, *http.Response, error) {
	return r.ApiService.UsersApiAdminUsageGetUsageExecute(r)
}

/*
UsersApiAdminUsageGetUsage Get Usage

Get usage and cost data for the Organization.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiUsersApiAdminUsageGetUsageRequest
*/
func (a *BetaAdminBillingAPIService) UsersApiAdminUsageGetUsage(ctx context.Context) ApiUsersApiAdminUsageGetUsageRequest {
	return ApiUsersApiAdminUsageGetUsageRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return UsageOUTJSON
func (a *BetaAdminBillingAPIService) UsersApiAdminUsageGetUsageExecute(r ApiUsersApiAdminUsageGetUsageRequest) (*UsageOUTJSON, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UsageOUTJSON
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaAdminBillingAPIService.UsersApiAdminUsageGetUsage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/admin/usage"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.month != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "month", r.month, "form", "")
	}
	if r.year != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "year", r.year, "form", "")
	}
	if r.workspaceId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "workspace_id", r.workspaceId, "form", "")
	}
	if r.apiZone != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api_zone", r.apiZone, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
