/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)


type BetaObservabilityLogsAPI interface {

	/*
	GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGet Get options for a log field

	Get options for a log field

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param fieldName
	@return ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest
	*/
	GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGet(ctx context.Context, fieldName string) ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest

	// GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetExecute executes the request
	//  @return GetLogFieldOptions
	GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetExecute(r ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest) (*GetLogFieldOptions, *http.Response, error)

	/*
	GetLogFieldsV1ObservabilityLogsFieldsGet Get log field definitions

	Get log field definitions

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest
	*/
	GetLogFieldsV1ObservabilityLogsFieldsGet(ctx context.Context) ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest

	// GetLogFieldsV1ObservabilityLogsFieldsGetExecute executes the request
	//  @return GetLogFields
	GetLogFieldsV1ObservabilityLogsFieldsGetExecute(r ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest) (*GetLogFields, *http.Response, error)

	/*
	SearchLogsV1ObservabilityLogsSearchPost Search logs

	Search logs

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiSearchLogsV1ObservabilityLogsSearchPostRequest
	*/
	SearchLogsV1ObservabilityLogsSearchPost(ctx context.Context) ApiSearchLogsV1ObservabilityLogsSearchPostRequest

	// SearchLogsV1ObservabilityLogsSearchPostExecute executes the request
	//  @return GetLogs
	SearchLogsV1ObservabilityLogsSearchPostExecute(r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) (*GetLogs, *http.Response, error)
}

// BetaObservabilityLogsAPIService BetaObservabilityLogsAPI service
type BetaObservabilityLogsAPIService service

type ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest struct {
	ctx context.Context
	ApiService BetaObservabilityLogsAPI
	fieldName string
	from *time.Time
	to *time.Time
}

func (r ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest) From(from time.Time) ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest {
	r.from = &from
	return r
}

func (r ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest) To(to time.Time) ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest {
	r.to = &to
	return r
}

func (r ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest) Execute() (*GetLogFieldOptions, *http.Response, error) {
	return r.ApiService.GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetExecute(r)
}

/*
GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGet Get options for a log field

Get options for a log field

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fieldName
 @return ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest
*/
func (a *BetaObservabilityLogsAPIService) GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGet(ctx context.Context, fieldName string) ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest {
	return ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest{
		ApiService: a,
		ctx: ctx,
		fieldName: fieldName,
	}
}

// Execute executes the request
//  @return GetLogFieldOptions
func (a *BetaObservabilityLogsAPIService) GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetExecute(r ApiGetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGetRequest) (*GetLogFieldOptions, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetLogFieldOptions
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityLogsAPIService.GetLogFieldOptionsV1ObservabilityLogsFieldsFieldNameOptionsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/logs/fields/{field_name}/options"
	localVarPath = strings.Replace(localVarPath, "{"+"field_name"+"}", url.PathEscape(parameterValueToString(r.fieldName, "fieldName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest struct {
	ctx context.Context
	ApiService BetaObservabilityLogsAPI
}

func (r ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest) Execute() (*GetLogFields, *http.Response, error) {
	return r.ApiService.GetLogFieldsV1ObservabilityLogsFieldsGetExecute(r)
}

/*
GetLogFieldsV1ObservabilityLogsFieldsGet Get log field definitions

Get log field definitions

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest
*/
func (a *BetaObservabilityLogsAPIService) GetLogFieldsV1ObservabilityLogsFieldsGet(ctx context.Context) ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest {
	return ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetLogFields
func (a *BetaObservabilityLogsAPIService) GetLogFieldsV1ObservabilityLogsFieldsGetExecute(r ApiGetLogFieldsV1ObservabilityLogsFieldsGetRequest) (*GetLogFields, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetLogFields
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityLogsAPIService.GetLogFieldsV1ObservabilityLogsFieldsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/logs/fields"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiSearchLogsV1ObservabilityLogsSearchPostRequest struct {
	ctx context.Context
	ApiService BetaObservabilityLogsAPI
	logsRequest *LogsRequest
	from *time.Time
	to *time.Time
	pageSize *int32
	cursor *string
}

func (r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) LogsRequest(logsRequest LogsRequest) ApiSearchLogsV1ObservabilityLogsSearchPostRequest {
	r.logsRequest = &logsRequest
	return r
}

func (r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) From(from time.Time) ApiSearchLogsV1ObservabilityLogsSearchPostRequest {
	r.from = &from
	return r
}

func (r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) To(to time.Time) ApiSearchLogsV1ObservabilityLogsSearchPostRequest {
	r.to = &to
	return r
}

func (r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) PageSize(pageSize int32) ApiSearchLogsV1ObservabilityLogsSearchPostRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) Cursor(cursor string) ApiSearchLogsV1ObservabilityLogsSearchPostRequest {
	r.cursor = &cursor
	return r
}

func (r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) Execute() (*GetLogs, *http.Response, error) {
	return r.ApiService.SearchLogsV1ObservabilityLogsSearchPostExecute(r)
}

/*
SearchLogsV1ObservabilityLogsSearchPost Search logs

Search logs

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiSearchLogsV1ObservabilityLogsSearchPostRequest
*/
func (a *BetaObservabilityLogsAPIService) SearchLogsV1ObservabilityLogsSearchPost(ctx context.Context) ApiSearchLogsV1ObservabilityLogsSearchPostRequest {
	return ApiSearchLogsV1ObservabilityLogsSearchPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return GetLogs
func (a *BetaObservabilityLogsAPIService) SearchLogsV1ObservabilityLogsSearchPostExecute(r ApiSearchLogsV1ObservabilityLogsSearchPostRequest) (*GetLogs, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetLogs
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BetaObservabilityLogsAPIService.SearchLogsV1ObservabilityLogsSearchPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/observability/logs/search"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.logsRequest == nil {
		return localVarReturnValue, nil, reportError("logsRequest is required and must be specified")
	}

	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "form", "")
	} else {
		var defaultValue int32 = 50
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.logsRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 408 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ObservabilityError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
