/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the LimitsOUT type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LimitsOUT{}

// LimitsOUT struct for LimitsOUT
type LimitsOUT struct {
	// Usage, rate, and job limits for the Organization.
	Limits LimitsContext `json:"limits"`
	AdditionalProperties map[string]interface{}
}

type _LimitsOUT LimitsOUT

// NewLimitsOUT instantiates a new LimitsOUT object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLimitsOUT(limits LimitsContext) *LimitsOUT {
	this := LimitsOUT{}
	this.Limits = limits
	return &this
}

// NewLimitsOUTWithDefaults instantiates a new LimitsOUT object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLimitsOUTWithDefaults() *LimitsOUT {
	this := LimitsOUT{}
	return &this
}

// GetLimits returns the Limits field value
func (o *LimitsOUT) GetLimits() LimitsContext {
	if o == nil {
		var ret LimitsContext
		return ret
	}

	return o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value
// and a boolean to check if the value has been set.
func (o *LimitsOUT) GetLimitsOk() (*LimitsContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limits, true
}

// SetLimits sets field value
func (o *LimitsOUT) SetLimits(v LimitsContext) {
	o.Limits = v
}

func (o LimitsOUT) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LimitsOUT) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["limits"] = o.Limits

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LimitsOUT) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"limits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLimitsOUT := _LimitsOUT{}

	err = json.Unmarshal(data, &varLimitsOUT)

	if err != nil {
		return err
	}

	*o = LimitsOUT(varLimitsOUT)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "limits")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLimitsOUT struct {
	value *LimitsOUT
	isSet bool
}

func (v NullableLimitsOUT) Get() *LimitsOUT {
	return v.value
}

func (v *NullableLimitsOUT) Set(val *LimitsOUT) {
	v.value = val
	v.isSet = true
}

func (v NullableLimitsOUT) IsSet() bool {
	return v.isSet
}

func (v *NullableLimitsOUT) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLimitsOUT(val *LimitsOUT) *NullableLimitsOUT {
	return &NullableLimitsOUT{value: val, isSet: true}
}

func (v NullableLimitsOUT) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLimitsOUT) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
