/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the QueryInvocationBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryInvocationBody{}

// QueryInvocationBody struct for QueryInvocationBody
type QueryInvocationBody struct {
	Input NullableInput2 `json:"input,omitempty"`
	// The name of the query to request
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _QueryInvocationBody QueryInvocationBody

// NewQueryInvocationBody instantiates a new QueryInvocationBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryInvocationBody(name string) *QueryInvocationBody {
	this := QueryInvocationBody{}
	this.Name = name
	return &this
}

// NewQueryInvocationBodyWithDefaults instantiates a new QueryInvocationBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryInvocationBodyWithDefaults() *QueryInvocationBody {
	this := QueryInvocationBody{}
	return &this
}

// GetInput returns the Input field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryInvocationBody) GetInput() Input2 {
	if o == nil || IsNil(o.Input.Get()) {
		var ret Input2
		return ret
	}
	return *o.Input.Get()
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryInvocationBody) GetInputOk() (*Input2, bool) {
	if o == nil {
		return nil, false
	}
	return o.Input.Get(), o.Input.IsSet()
}

// HasInput returns a boolean if a field has been set.
func (o *QueryInvocationBody) HasInput() bool {
	if o != nil && o.Input.IsSet() {
		return true
	}

	return false
}

// SetInput gets a reference to the given NullableInput2 and assigns it to the Input field.
func (o *QueryInvocationBody) SetInput(v Input2) {
	o.Input.Set(&v)
}
// SetInputNil sets the value for Input to be an explicit nil
func (o *QueryInvocationBody) SetInputNil() {
	o.Input.Set(nil)
}

// UnsetInput ensures that no value is present for Input, not even an explicit nil
func (o *QueryInvocationBody) UnsetInput() {
	o.Input.Unset()
}

// GetName returns the Name field value
func (o *QueryInvocationBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *QueryInvocationBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *QueryInvocationBody) SetName(v string) {
	o.Name = v
}

func (o QueryInvocationBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryInvocationBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Input.IsSet() {
		toSerialize["input"] = o.Input.Get()
	}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QueryInvocationBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryInvocationBody := _QueryInvocationBody{}

	err = json.Unmarshal(data, &varQueryInvocationBody)

	if err != nil {
		return err
	}

	*o = QueryInvocationBody(varQueryInvocationBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "input")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQueryInvocationBody struct {
	value *QueryInvocationBody
	isSet bool
}

func (v NullableQueryInvocationBody) Get() *QueryInvocationBody {
	return v.value
}

func (v *NullableQueryInvocationBody) Set(val *QueryInvocationBody) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryInvocationBody) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryInvocationBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryInvocationBody(val *QueryInvocationBody) *NullableQueryInvocationBody {
	return &NullableQueryInvocationBody{value: val, isSet: true}
}

func (v NullableQueryInvocationBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryInvocationBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
