/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)


// Input3 Input data for the signal, matching its schema
type Input3 struct {
	NetworkEncodedInput *NetworkEncodedInput
	MapmapOfStringAny *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Input3) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into NetworkEncodedInput
	err = json.Unmarshal(data, &dst.NetworkEncodedInput);
	if err == nil {
		jsonNetworkEncodedInput, _ := json.Marshal(dst.NetworkEncodedInput)
		if string(jsonNetworkEncodedInput) == "{}" { // empty struct
			dst.NetworkEncodedInput = nil
		} else {
			return nil // data stored in dst.NetworkEncodedInput, return on the first match
		}
	} else {
		dst.NetworkEncodedInput = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny);
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Input3)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Input3) MarshalJSON() ([]byte, error) {
	if src.NetworkEncodedInput != nil {
		return json.Marshal(&src.NetworkEncodedInput)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableInput3 struct {
	value *Input3
	isSet bool
}

func (v NullableInput3) Get() *Input3 {
	return v.value
}

func (v *NullableInput3) Set(val *Input3) {
	v.value = val
	v.isSet = true
}

func (v NullableInput3) IsSet() bool {
	return v.isSet
}

func (v *NullableInput3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInput3(val *Input3) *NullableInput3 {
	return &NullableInput3{value: val, isSet: true}
}

func (v NullableInput3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInput3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
