/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// EventsInner - struct for EventsInner
type EventsInner struct {
	ActivityTaskCompletedResponse           *ActivityTaskCompletedResponse
	ActivityTaskFailedResponse              *ActivityTaskFailedResponse
	ActivityTaskRetryingResponse            *ActivityTaskRetryingResponse
	ActivityTaskStartedResponse             *ActivityTaskStartedResponse
	CustomTaskCanceledResponse              *CustomTaskCanceledResponse
	CustomTaskCompletedResponse             *CustomTaskCompletedResponse
	CustomTaskFailedResponse                *CustomTaskFailedResponse
	CustomTaskInProgressResponse            *CustomTaskInProgressResponse
	CustomTaskStartedResponse               *CustomTaskStartedResponse
	CustomTaskTimedOutResponse              *CustomTaskTimedOutResponse
	WorkflowExecutionCanceledResponse       *WorkflowExecutionCanceledResponse
	WorkflowExecutionCompletedResponse      *WorkflowExecutionCompletedResponse
	WorkflowExecutionContinuedAsNewResponse *WorkflowExecutionContinuedAsNewResponse
	WorkflowExecutionFailedResponse         *WorkflowExecutionFailedResponse
	WorkflowExecutionStartedResponse        *WorkflowExecutionStartedResponse
	WorkflowTaskFailedResponse              *WorkflowTaskFailedResponse
	WorkflowTaskTimedOutResponse            *WorkflowTaskTimedOutResponse
}

// ActivityTaskCompletedResponseAsEventsInner is a convenience function that returns ActivityTaskCompletedResponse wrapped in EventsInner
func ActivityTaskCompletedResponseAsEventsInner(v *ActivityTaskCompletedResponse) EventsInner {
	return EventsInner{
		ActivityTaskCompletedResponse: v,
	}
}

// ActivityTaskFailedResponseAsEventsInner is a convenience function that returns ActivityTaskFailedResponse wrapped in EventsInner
func ActivityTaskFailedResponseAsEventsInner(v *ActivityTaskFailedResponse) EventsInner {
	return EventsInner{
		ActivityTaskFailedResponse: v,
	}
}

// ActivityTaskRetryingResponseAsEventsInner is a convenience function that returns ActivityTaskRetryingResponse wrapped in EventsInner
func ActivityTaskRetryingResponseAsEventsInner(v *ActivityTaskRetryingResponse) EventsInner {
	return EventsInner{
		ActivityTaskRetryingResponse: v,
	}
}

// ActivityTaskStartedResponseAsEventsInner is a convenience function that returns ActivityTaskStartedResponse wrapped in EventsInner
func ActivityTaskStartedResponseAsEventsInner(v *ActivityTaskStartedResponse) EventsInner {
	return EventsInner{
		ActivityTaskStartedResponse: v,
	}
}

// CustomTaskCanceledResponseAsEventsInner is a convenience function that returns CustomTaskCanceledResponse wrapped in EventsInner
func CustomTaskCanceledResponseAsEventsInner(v *CustomTaskCanceledResponse) EventsInner {
	return EventsInner{
		CustomTaskCanceledResponse: v,
	}
}

// CustomTaskCompletedResponseAsEventsInner is a convenience function that returns CustomTaskCompletedResponse wrapped in EventsInner
func CustomTaskCompletedResponseAsEventsInner(v *CustomTaskCompletedResponse) EventsInner {
	return EventsInner{
		CustomTaskCompletedResponse: v,
	}
}

// CustomTaskFailedResponseAsEventsInner is a convenience function that returns CustomTaskFailedResponse wrapped in EventsInner
func CustomTaskFailedResponseAsEventsInner(v *CustomTaskFailedResponse) EventsInner {
	return EventsInner{
		CustomTaskFailedResponse: v,
	}
}

// CustomTaskInProgressResponseAsEventsInner is a convenience function that returns CustomTaskInProgressResponse wrapped in EventsInner
func CustomTaskInProgressResponseAsEventsInner(v *CustomTaskInProgressResponse) EventsInner {
	return EventsInner{
		CustomTaskInProgressResponse: v,
	}
}

// CustomTaskStartedResponseAsEventsInner is a convenience function that returns CustomTaskStartedResponse wrapped in EventsInner
func CustomTaskStartedResponseAsEventsInner(v *CustomTaskStartedResponse) EventsInner {
	return EventsInner{
		CustomTaskStartedResponse: v,
	}
}

// CustomTaskTimedOutResponseAsEventsInner is a convenience function that returns CustomTaskTimedOutResponse wrapped in EventsInner
func CustomTaskTimedOutResponseAsEventsInner(v *CustomTaskTimedOutResponse) EventsInner {
	return EventsInner{
		CustomTaskTimedOutResponse: v,
	}
}

// WorkflowExecutionCanceledResponseAsEventsInner is a convenience function that returns WorkflowExecutionCanceledResponse wrapped in EventsInner
func WorkflowExecutionCanceledResponseAsEventsInner(v *WorkflowExecutionCanceledResponse) EventsInner {
	return EventsInner{
		WorkflowExecutionCanceledResponse: v,
	}
}

// WorkflowExecutionCompletedResponseAsEventsInner is a convenience function that returns WorkflowExecutionCompletedResponse wrapped in EventsInner
func WorkflowExecutionCompletedResponseAsEventsInner(v *WorkflowExecutionCompletedResponse) EventsInner {
	return EventsInner{
		WorkflowExecutionCompletedResponse: v,
	}
}

// WorkflowExecutionContinuedAsNewResponseAsEventsInner is a convenience function that returns WorkflowExecutionContinuedAsNewResponse wrapped in EventsInner
func WorkflowExecutionContinuedAsNewResponseAsEventsInner(v *WorkflowExecutionContinuedAsNewResponse) EventsInner {
	return EventsInner{
		WorkflowExecutionContinuedAsNewResponse: v,
	}
}

// WorkflowExecutionFailedResponseAsEventsInner is a convenience function that returns WorkflowExecutionFailedResponse wrapped in EventsInner
func WorkflowExecutionFailedResponseAsEventsInner(v *WorkflowExecutionFailedResponse) EventsInner {
	return EventsInner{
		WorkflowExecutionFailedResponse: v,
	}
}

// WorkflowExecutionStartedResponseAsEventsInner is a convenience function that returns WorkflowExecutionStartedResponse wrapped in EventsInner
func WorkflowExecutionStartedResponseAsEventsInner(v *WorkflowExecutionStartedResponse) EventsInner {
	return EventsInner{
		WorkflowExecutionStartedResponse: v,
	}
}

// WorkflowTaskFailedResponseAsEventsInner is a convenience function that returns WorkflowTaskFailedResponse wrapped in EventsInner
func WorkflowTaskFailedResponseAsEventsInner(v *WorkflowTaskFailedResponse) EventsInner {
	return EventsInner{
		WorkflowTaskFailedResponse: v,
	}
}

// WorkflowTaskTimedOutResponseAsEventsInner is a convenience function that returns WorkflowTaskTimedOutResponse wrapped in EventsInner
func WorkflowTaskTimedOutResponseAsEventsInner(v *WorkflowTaskTimedOutResponse) EventsInner {
	return EventsInner{
		WorkflowTaskTimedOutResponse: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *EventsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ActivityTaskCompletedResponse
	err = newStrictDecoder(data).Decode(&dst.ActivityTaskCompletedResponse)
	if err == nil {
		jsonActivityTaskCompletedResponse, _ := json.Marshal(dst.ActivityTaskCompletedResponse)
		if string(jsonActivityTaskCompletedResponse) == "{}" { // empty struct
			dst.ActivityTaskCompletedResponse = nil
		} else {
			if err = validator.Validate(dst.ActivityTaskCompletedResponse); err != nil {
				dst.ActivityTaskCompletedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.ActivityTaskCompletedResponse = nil
	}

	// try to unmarshal data into ActivityTaskFailedResponse
	err = newStrictDecoder(data).Decode(&dst.ActivityTaskFailedResponse)
	if err == nil {
		jsonActivityTaskFailedResponse, _ := json.Marshal(dst.ActivityTaskFailedResponse)
		if string(jsonActivityTaskFailedResponse) == "{}" { // empty struct
			dst.ActivityTaskFailedResponse = nil
		} else {
			if err = validator.Validate(dst.ActivityTaskFailedResponse); err != nil {
				dst.ActivityTaskFailedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.ActivityTaskFailedResponse = nil
	}

	// try to unmarshal data into ActivityTaskRetryingResponse
	err = newStrictDecoder(data).Decode(&dst.ActivityTaskRetryingResponse)
	if err == nil {
		jsonActivityTaskRetryingResponse, _ := json.Marshal(dst.ActivityTaskRetryingResponse)
		if string(jsonActivityTaskRetryingResponse) == "{}" { // empty struct
			dst.ActivityTaskRetryingResponse = nil
		} else {
			if err = validator.Validate(dst.ActivityTaskRetryingResponse); err != nil {
				dst.ActivityTaskRetryingResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.ActivityTaskRetryingResponse = nil
	}

	// try to unmarshal data into ActivityTaskStartedResponse
	err = newStrictDecoder(data).Decode(&dst.ActivityTaskStartedResponse)
	if err == nil {
		jsonActivityTaskStartedResponse, _ := json.Marshal(dst.ActivityTaskStartedResponse)
		if string(jsonActivityTaskStartedResponse) == "{}" { // empty struct
			dst.ActivityTaskStartedResponse = nil
		} else {
			if err = validator.Validate(dst.ActivityTaskStartedResponse); err != nil {
				dst.ActivityTaskStartedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.ActivityTaskStartedResponse = nil
	}

	// try to unmarshal data into CustomTaskCanceledResponse
	err = newStrictDecoder(data).Decode(&dst.CustomTaskCanceledResponse)
	if err == nil {
		jsonCustomTaskCanceledResponse, _ := json.Marshal(dst.CustomTaskCanceledResponse)
		if string(jsonCustomTaskCanceledResponse) == "{}" { // empty struct
			dst.CustomTaskCanceledResponse = nil
		} else {
			if err = validator.Validate(dst.CustomTaskCanceledResponse); err != nil {
				dst.CustomTaskCanceledResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomTaskCanceledResponse = nil
	}

	// try to unmarshal data into CustomTaskCompletedResponse
	err = newStrictDecoder(data).Decode(&dst.CustomTaskCompletedResponse)
	if err == nil {
		jsonCustomTaskCompletedResponse, _ := json.Marshal(dst.CustomTaskCompletedResponse)
		if string(jsonCustomTaskCompletedResponse) == "{}" { // empty struct
			dst.CustomTaskCompletedResponse = nil
		} else {
			if err = validator.Validate(dst.CustomTaskCompletedResponse); err != nil {
				dst.CustomTaskCompletedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomTaskCompletedResponse = nil
	}

	// try to unmarshal data into CustomTaskFailedResponse
	err = newStrictDecoder(data).Decode(&dst.CustomTaskFailedResponse)
	if err == nil {
		jsonCustomTaskFailedResponse, _ := json.Marshal(dst.CustomTaskFailedResponse)
		if string(jsonCustomTaskFailedResponse) == "{}" { // empty struct
			dst.CustomTaskFailedResponse = nil
		} else {
			if err = validator.Validate(dst.CustomTaskFailedResponse); err != nil {
				dst.CustomTaskFailedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomTaskFailedResponse = nil
	}

	// try to unmarshal data into CustomTaskInProgressResponse
	err = newStrictDecoder(data).Decode(&dst.CustomTaskInProgressResponse)
	if err == nil {
		jsonCustomTaskInProgressResponse, _ := json.Marshal(dst.CustomTaskInProgressResponse)
		if string(jsonCustomTaskInProgressResponse) == "{}" { // empty struct
			dst.CustomTaskInProgressResponse = nil
		} else {
			if err = validator.Validate(dst.CustomTaskInProgressResponse); err != nil {
				dst.CustomTaskInProgressResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomTaskInProgressResponse = nil
	}

	// try to unmarshal data into CustomTaskStartedResponse
	err = newStrictDecoder(data).Decode(&dst.CustomTaskStartedResponse)
	if err == nil {
		jsonCustomTaskStartedResponse, _ := json.Marshal(dst.CustomTaskStartedResponse)
		if string(jsonCustomTaskStartedResponse) == "{}" { // empty struct
			dst.CustomTaskStartedResponse = nil
		} else {
			if err = validator.Validate(dst.CustomTaskStartedResponse); err != nil {
				dst.CustomTaskStartedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomTaskStartedResponse = nil
	}

	// try to unmarshal data into CustomTaskTimedOutResponse
	err = newStrictDecoder(data).Decode(&dst.CustomTaskTimedOutResponse)
	if err == nil {
		jsonCustomTaskTimedOutResponse, _ := json.Marshal(dst.CustomTaskTimedOutResponse)
		if string(jsonCustomTaskTimedOutResponse) == "{}" { // empty struct
			dst.CustomTaskTimedOutResponse = nil
		} else {
			if err = validator.Validate(dst.CustomTaskTimedOutResponse); err != nil {
				dst.CustomTaskTimedOutResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomTaskTimedOutResponse = nil
	}

	// try to unmarshal data into WorkflowExecutionCanceledResponse
	err = newStrictDecoder(data).Decode(&dst.WorkflowExecutionCanceledResponse)
	if err == nil {
		jsonWorkflowExecutionCanceledResponse, _ := json.Marshal(dst.WorkflowExecutionCanceledResponse)
		if string(jsonWorkflowExecutionCanceledResponse) == "{}" { // empty struct
			dst.WorkflowExecutionCanceledResponse = nil
		} else {
			if err = validator.Validate(dst.WorkflowExecutionCanceledResponse); err != nil {
				dst.WorkflowExecutionCanceledResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkflowExecutionCanceledResponse = nil
	}

	// try to unmarshal data into WorkflowExecutionCompletedResponse
	err = newStrictDecoder(data).Decode(&dst.WorkflowExecutionCompletedResponse)
	if err == nil {
		jsonWorkflowExecutionCompletedResponse, _ := json.Marshal(dst.WorkflowExecutionCompletedResponse)
		if string(jsonWorkflowExecutionCompletedResponse) == "{}" { // empty struct
			dst.WorkflowExecutionCompletedResponse = nil
		} else {
			if err = validator.Validate(dst.WorkflowExecutionCompletedResponse); err != nil {
				dst.WorkflowExecutionCompletedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkflowExecutionCompletedResponse = nil
	}

	// try to unmarshal data into WorkflowExecutionContinuedAsNewResponse
	err = newStrictDecoder(data).Decode(&dst.WorkflowExecutionContinuedAsNewResponse)
	if err == nil {
		jsonWorkflowExecutionContinuedAsNewResponse, _ := json.Marshal(dst.WorkflowExecutionContinuedAsNewResponse)
		if string(jsonWorkflowExecutionContinuedAsNewResponse) == "{}" { // empty struct
			dst.WorkflowExecutionContinuedAsNewResponse = nil
		} else {
			if err = validator.Validate(dst.WorkflowExecutionContinuedAsNewResponse); err != nil {
				dst.WorkflowExecutionContinuedAsNewResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkflowExecutionContinuedAsNewResponse = nil
	}

	// try to unmarshal data into WorkflowExecutionFailedResponse
	err = newStrictDecoder(data).Decode(&dst.WorkflowExecutionFailedResponse)
	if err == nil {
		jsonWorkflowExecutionFailedResponse, _ := json.Marshal(dst.WorkflowExecutionFailedResponse)
		if string(jsonWorkflowExecutionFailedResponse) == "{}" { // empty struct
			dst.WorkflowExecutionFailedResponse = nil
		} else {
			if err = validator.Validate(dst.WorkflowExecutionFailedResponse); err != nil {
				dst.WorkflowExecutionFailedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkflowExecutionFailedResponse = nil
	}

	// try to unmarshal data into WorkflowExecutionStartedResponse
	err = newStrictDecoder(data).Decode(&dst.WorkflowExecutionStartedResponse)
	if err == nil {
		jsonWorkflowExecutionStartedResponse, _ := json.Marshal(dst.WorkflowExecutionStartedResponse)
		if string(jsonWorkflowExecutionStartedResponse) == "{}" { // empty struct
			dst.WorkflowExecutionStartedResponse = nil
		} else {
			if err = validator.Validate(dst.WorkflowExecutionStartedResponse); err != nil {
				dst.WorkflowExecutionStartedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkflowExecutionStartedResponse = nil
	}

	// try to unmarshal data into WorkflowTaskFailedResponse
	err = newStrictDecoder(data).Decode(&dst.WorkflowTaskFailedResponse)
	if err == nil {
		jsonWorkflowTaskFailedResponse, _ := json.Marshal(dst.WorkflowTaskFailedResponse)
		if string(jsonWorkflowTaskFailedResponse) == "{}" { // empty struct
			dst.WorkflowTaskFailedResponse = nil
		} else {
			if err = validator.Validate(dst.WorkflowTaskFailedResponse); err != nil {
				dst.WorkflowTaskFailedResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkflowTaskFailedResponse = nil
	}

	// try to unmarshal data into WorkflowTaskTimedOutResponse
	err = newStrictDecoder(data).Decode(&dst.WorkflowTaskTimedOutResponse)
	if err == nil {
		jsonWorkflowTaskTimedOutResponse, _ := json.Marshal(dst.WorkflowTaskTimedOutResponse)
		if string(jsonWorkflowTaskTimedOutResponse) == "{}" { // empty struct
			dst.WorkflowTaskTimedOutResponse = nil
		} else {
			if err = validator.Validate(dst.WorkflowTaskTimedOutResponse); err != nil {
				dst.WorkflowTaskTimedOutResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkflowTaskTimedOutResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ActivityTaskCompletedResponse = nil
		dst.ActivityTaskFailedResponse = nil
		dst.ActivityTaskRetryingResponse = nil
		dst.ActivityTaskStartedResponse = nil
		dst.CustomTaskCanceledResponse = nil
		dst.CustomTaskCompletedResponse = nil
		dst.CustomTaskFailedResponse = nil
		dst.CustomTaskInProgressResponse = nil
		dst.CustomTaskStartedResponse = nil
		dst.CustomTaskTimedOutResponse = nil
		dst.WorkflowExecutionCanceledResponse = nil
		dst.WorkflowExecutionCompletedResponse = nil
		dst.WorkflowExecutionContinuedAsNewResponse = nil
		dst.WorkflowExecutionFailedResponse = nil
		dst.WorkflowExecutionStartedResponse = nil
		dst.WorkflowTaskFailedResponse = nil
		dst.WorkflowTaskTimedOutResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(EventsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(EventsInner): %v", err)
		} else {
			return fmt.Errorf("data failed to match schemas in oneOf(EventsInner)")
		}

	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EventsInner) MarshalJSON() ([]byte, error) {
	if src.ActivityTaskCompletedResponse != nil {
		return json.Marshal(&src.ActivityTaskCompletedResponse)
	}

	if src.ActivityTaskFailedResponse != nil {
		return json.Marshal(&src.ActivityTaskFailedResponse)
	}

	if src.ActivityTaskRetryingResponse != nil {
		return json.Marshal(&src.ActivityTaskRetryingResponse)
	}

	if src.ActivityTaskStartedResponse != nil {
		return json.Marshal(&src.ActivityTaskStartedResponse)
	}

	if src.CustomTaskCanceledResponse != nil {
		return json.Marshal(&src.CustomTaskCanceledResponse)
	}

	if src.CustomTaskCompletedResponse != nil {
		return json.Marshal(&src.CustomTaskCompletedResponse)
	}

	if src.CustomTaskFailedResponse != nil {
		return json.Marshal(&src.CustomTaskFailedResponse)
	}

	if src.CustomTaskInProgressResponse != nil {
		return json.Marshal(&src.CustomTaskInProgressResponse)
	}

	if src.CustomTaskStartedResponse != nil {
		return json.Marshal(&src.CustomTaskStartedResponse)
	}

	if src.CustomTaskTimedOutResponse != nil {
		return json.Marshal(&src.CustomTaskTimedOutResponse)
	}

	if src.WorkflowExecutionCanceledResponse != nil {
		return json.Marshal(&src.WorkflowExecutionCanceledResponse)
	}

	if src.WorkflowExecutionCompletedResponse != nil {
		return json.Marshal(&src.WorkflowExecutionCompletedResponse)
	}

	if src.WorkflowExecutionContinuedAsNewResponse != nil {
		return json.Marshal(&src.WorkflowExecutionContinuedAsNewResponse)
	}

	if src.WorkflowExecutionFailedResponse != nil {
		return json.Marshal(&src.WorkflowExecutionFailedResponse)
	}

	if src.WorkflowExecutionStartedResponse != nil {
		return json.Marshal(&src.WorkflowExecutionStartedResponse)
	}

	if src.WorkflowTaskFailedResponse != nil {
		return json.Marshal(&src.WorkflowTaskFailedResponse)
	}

	if src.WorkflowTaskTimedOutResponse != nil {
		return json.Marshal(&src.WorkflowTaskTimedOutResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *EventsInner) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ActivityTaskCompletedResponse != nil {
		return obj.ActivityTaskCompletedResponse
	}

	if obj.ActivityTaskFailedResponse != nil {
		return obj.ActivityTaskFailedResponse
	}

	if obj.ActivityTaskRetryingResponse != nil {
		return obj.ActivityTaskRetryingResponse
	}

	if obj.ActivityTaskStartedResponse != nil {
		return obj.ActivityTaskStartedResponse
	}

	if obj.CustomTaskCanceledResponse != nil {
		return obj.CustomTaskCanceledResponse
	}

	if obj.CustomTaskCompletedResponse != nil {
		return obj.CustomTaskCompletedResponse
	}

	if obj.CustomTaskFailedResponse != nil {
		return obj.CustomTaskFailedResponse
	}

	if obj.CustomTaskInProgressResponse != nil {
		return obj.CustomTaskInProgressResponse
	}

	if obj.CustomTaskStartedResponse != nil {
		return obj.CustomTaskStartedResponse
	}

	if obj.CustomTaskTimedOutResponse != nil {
		return obj.CustomTaskTimedOutResponse
	}

	if obj.WorkflowExecutionCanceledResponse != nil {
		return obj.WorkflowExecutionCanceledResponse
	}

	if obj.WorkflowExecutionCompletedResponse != nil {
		return obj.WorkflowExecutionCompletedResponse
	}

	if obj.WorkflowExecutionContinuedAsNewResponse != nil {
		return obj.WorkflowExecutionContinuedAsNewResponse
	}

	if obj.WorkflowExecutionFailedResponse != nil {
		return obj.WorkflowExecutionFailedResponse
	}

	if obj.WorkflowExecutionStartedResponse != nil {
		return obj.WorkflowExecutionStartedResponse
	}

	if obj.WorkflowTaskFailedResponse != nil {
		return obj.WorkflowTaskFailedResponse
	}

	if obj.WorkflowTaskTimedOutResponse != nil {
		return obj.WorkflowTaskTimedOutResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj EventsInner) GetActualInstanceValue() interface{} {
	if obj.ActivityTaskCompletedResponse != nil {
		return *obj.ActivityTaskCompletedResponse
	}

	if obj.ActivityTaskFailedResponse != nil {
		return *obj.ActivityTaskFailedResponse
	}

	if obj.ActivityTaskRetryingResponse != nil {
		return *obj.ActivityTaskRetryingResponse
	}

	if obj.ActivityTaskStartedResponse != nil {
		return *obj.ActivityTaskStartedResponse
	}

	if obj.CustomTaskCanceledResponse != nil {
		return *obj.CustomTaskCanceledResponse
	}

	if obj.CustomTaskCompletedResponse != nil {
		return *obj.CustomTaskCompletedResponse
	}

	if obj.CustomTaskFailedResponse != nil {
		return *obj.CustomTaskFailedResponse
	}

	if obj.CustomTaskInProgressResponse != nil {
		return *obj.CustomTaskInProgressResponse
	}

	if obj.CustomTaskStartedResponse != nil {
		return *obj.CustomTaskStartedResponse
	}

	if obj.CustomTaskTimedOutResponse != nil {
		return *obj.CustomTaskTimedOutResponse
	}

	if obj.WorkflowExecutionCanceledResponse != nil {
		return *obj.WorkflowExecutionCanceledResponse
	}

	if obj.WorkflowExecutionCompletedResponse != nil {
		return *obj.WorkflowExecutionCompletedResponse
	}

	if obj.WorkflowExecutionContinuedAsNewResponse != nil {
		return *obj.WorkflowExecutionContinuedAsNewResponse
	}

	if obj.WorkflowExecutionFailedResponse != nil {
		return *obj.WorkflowExecutionFailedResponse
	}

	if obj.WorkflowExecutionStartedResponse != nil {
		return *obj.WorkflowExecutionStartedResponse
	}

	if obj.WorkflowTaskFailedResponse != nil {
		return *obj.WorkflowTaskFailedResponse
	}

	if obj.WorkflowTaskTimedOutResponse != nil {
		return *obj.WorkflowTaskTimedOutResponse
	}

	// all schemas are nil
	return nil
}

type NullableEventsInner struct {
	value *EventsInner
	isSet bool
}

func (v NullableEventsInner) Get() *EventsInner {
	return v.value
}

func (v *NullableEventsInner) Set(val *EventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsInner(val *EventsInner) *NullableEventsInner {
	return &NullableEventsInner{value: val, isSet: true}
}

func (v NullableEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
