/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSpanFieldOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSpanFieldOptions{}

// GetSpanFieldOptions struct for GetSpanFieldOptions
type GetSpanFieldOptions struct {
	Options []string `json:"options"`
	AdditionalProperties map[string]interface{}
}

type _GetSpanFieldOptions GetSpanFieldOptions

// NewGetSpanFieldOptions instantiates a new GetSpanFieldOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSpanFieldOptions(options []string) *GetSpanFieldOptions {
	this := GetSpanFieldOptions{}
	this.Options = options
	return &this
}

// NewGetSpanFieldOptionsWithDefaults instantiates a new GetSpanFieldOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSpanFieldOptionsWithDefaults() *GetSpanFieldOptions {
	this := GetSpanFieldOptions{}
	return &this
}

// GetOptions returns the Options field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *GetSpanFieldOptions) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetSpanFieldOptions) GetOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *GetSpanFieldOptions) SetOptions(v []string) {
	o.Options = v
}

func (o GetSpanFieldOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSpanFieldOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSpanFieldOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"options",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSpanFieldOptions := _GetSpanFieldOptions{}

	err = json.Unmarshal(data, &varGetSpanFieldOptions)

	if err != nil {
		return err
	}

	*o = GetSpanFieldOptions(varGetSpanFieldOptions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSpanFieldOptions struct {
	value *GetSpanFieldOptions
	isSet bool
}

func (v NullableGetSpanFieldOptions) Get() *GetSpanFieldOptions {
	return v.value
}

func (v *NullableGetSpanFieldOptions) Set(val *GetSpanFieldOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSpanFieldOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSpanFieldOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSpanFieldOptions(val *GetSpanFieldOptions) *NullableGetSpanFieldOptions {
	return &NullableGetSpanFieldOptions{value: val, isSet: true}
}

func (v NullableGetSpanFieldOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSpanFieldOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
