/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"time"
)

// checks if the UpdateDocumentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDocumentRequest{}

// UpdateDocumentRequest struct for UpdateDocumentRequest
type UpdateDocumentRequest struct {
	Attributes map[string]UpdateDocumentRequestAttributesValue `json:"attributes,omitempty"`
	// If set, the document will be automatically deleted after this date.
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateDocumentRequest UpdateDocumentRequest

// NewUpdateDocumentRequest instantiates a new UpdateDocumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDocumentRequest() *UpdateDocumentRequest {
	this := UpdateDocumentRequest{}
	return &this
}

// NewUpdateDocumentRequestWithDefaults instantiates a new UpdateDocumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDocumentRequestWithDefaults() *UpdateDocumentRequest {
	this := UpdateDocumentRequest{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDocumentRequest) GetAttributes() map[string]UpdateDocumentRequestAttributesValue {
	if o == nil {
		var ret map[string]UpdateDocumentRequestAttributesValue
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDocumentRequest) GetAttributesOk() (map[string]UpdateDocumentRequestAttributesValue, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]UpdateDocumentRequestAttributesValue{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *UpdateDocumentRequest) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]UpdateDocumentRequestAttributesValue and assigns it to the Attributes field.
func (o *UpdateDocumentRequest) SetAttributes(v map[string]UpdateDocumentRequestAttributesValue) {
	o.Attributes = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDocumentRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDocumentRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *UpdateDocumentRequest) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *UpdateDocumentRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *UpdateDocumentRequest) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *UpdateDocumentRequest) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateDocumentRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDocumentRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateDocumentRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateDocumentRequest) SetName(v string) {
	o.Name = &v
}

func (o UpdateDocumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDocumentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateDocumentRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateDocumentRequest := _UpdateDocumentRequest{}

	err = json.Unmarshal(data, &varUpdateDocumentRequest)

	if err != nil {
		return err
	}

	*o = UpdateDocumentRequest(varUpdateDocumentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateDocumentRequest struct {
	value *UpdateDocumentRequest
	isSet bool
}

func (v NullableUpdateDocumentRequest) Get() *UpdateDocumentRequest {
	return v.value
}

func (v *NullableUpdateDocumentRequest) Set(val *UpdateDocumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDocumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDocumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDocumentRequest(val *UpdateDocumentRequest) *NullableUpdateDocumentRequest {
	return &NullableUpdateDocumentRequest{value: val, isSet: true}
}

func (v NullableUpdateDocumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDocumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
