/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the GetLogFieldOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLogFieldOptions{}

// GetLogFieldOptions struct for GetLogFieldOptions
type GetLogFieldOptions struct {
	Options []string `json:"options"`
	AdditionalProperties map[string]interface{}
}

type _GetLogFieldOptions GetLogFieldOptions

// NewGetLogFieldOptions instantiates a new GetLogFieldOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLogFieldOptions(options []string) *GetLogFieldOptions {
	this := GetLogFieldOptions{}
	this.Options = options
	return &this
}

// NewGetLogFieldOptionsWithDefaults instantiates a new GetLogFieldOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLogFieldOptionsWithDefaults() *GetLogFieldOptions {
	this := GetLogFieldOptions{}
	return &this
}

// GetOptions returns the Options field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *GetLogFieldOptions) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetLogFieldOptions) GetOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *GetLogFieldOptions) SetOptions(v []string) {
	o.Options = v
}

func (o GetLogFieldOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLogFieldOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetLogFieldOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"options",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetLogFieldOptions := _GetLogFieldOptions{}

	err = json.Unmarshal(data, &varGetLogFieldOptions)

	if err != nil {
		return err
	}

	*o = GetLogFieldOptions(varGetLogFieldOptions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetLogFieldOptions struct {
	value *GetLogFieldOptions
	isSet bool
}

func (v NullableGetLogFieldOptions) Get() *GetLogFieldOptions {
	return v.value
}

func (v *NullableGetLogFieldOptions) Set(val *GetLogFieldOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLogFieldOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLogFieldOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLogFieldOptions(val *GetLogFieldOptions) *NullableGetLogFieldOptions {
	return &NullableGetLogFieldOptions{value: val, isSet: true}
}

func (v NullableGetLogFieldOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLogFieldOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
