/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)


// RefAudio The audio reference for generating the speech.
type RefAudio struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RefAudio) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(RefAudio)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RefAudio) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableRefAudio struct {
	value *RefAudio
	isSet bool
}

func (v NullableRefAudio) Get() *RefAudio {
	return v.value
}

func (v *NullableRefAudio) Set(val *RefAudio) {
	v.value = val
	v.isSet = true
}

func (v NullableRefAudio) IsSet() bool {
	return v.isSet
}

func (v *NullableRefAudio) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefAudio(val *RefAudio) *NullableRefAudio {
	return &NullableRefAudio{value: val, isSet: true}
}

func (v NullableRefAudio) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefAudio) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
