/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
)

// checks if the ModerationLLMV2Config type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModerationLLMV2Config{}

// ModerationLLMV2Config struct for ModerationLLMV2Config
type ModerationLLMV2Config struct {
	// Action to take if any score is above the threshold for any category.
	Action *ModerationLLMAction `json:"action,omitempty"`
	CustomCategoryThresholds NullableModerationLLMV2CategoryThresholds `json:"custom_category_thresholds,omitempty"`
	// If true, only evaluate categories in custom_category_thresholds; others are ignored.
	IgnoreOtherCategories *bool `json:"ignore_other_categories,omitempty"`
	// Override model name. Should be omitted in general.
	ModelName *string `json:"model_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModerationLLMV2Config ModerationLLMV2Config

// NewModerationLLMV2Config instantiates a new ModerationLLMV2Config object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModerationLLMV2Config() *ModerationLLMV2Config {
	this := ModerationLLMV2Config{}
	var action ModerationLLMAction = MODERATIONLLMACTION_NONE
	this.Action = &action
	var ignoreOtherCategories bool = false
	this.IgnoreOtherCategories = &ignoreOtherCategories
	var modelName string = "mistral-moderation-2603"
	this.ModelName = &modelName
	return &this
}

// NewModerationLLMV2ConfigWithDefaults instantiates a new ModerationLLMV2Config object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModerationLLMV2ConfigWithDefaults() *ModerationLLMV2Config {
	this := ModerationLLMV2Config{}
	var action ModerationLLMAction = MODERATIONLLMACTION_NONE
	this.Action = &action
	var ignoreOtherCategories bool = false
	this.IgnoreOtherCategories = &ignoreOtherCategories
	var modelName string = "mistral-moderation-2603"
	this.ModelName = &modelName
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *ModerationLLMV2Config) GetAction() ModerationLLMAction {
	if o == nil || IsNil(o.Action) {
		var ret ModerationLLMAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModerationLLMV2Config) GetActionOk() (*ModerationLLMAction, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *ModerationLLMV2Config) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given ModerationLLMAction and assigns it to the Action field.
func (o *ModerationLLMV2Config) SetAction(v ModerationLLMAction) {
	o.Action = &v
}

// GetCustomCategoryThresholds returns the CustomCategoryThresholds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModerationLLMV2Config) GetCustomCategoryThresholds() ModerationLLMV2CategoryThresholds {
	if o == nil || IsNil(o.CustomCategoryThresholds.Get()) {
		var ret ModerationLLMV2CategoryThresholds
		return ret
	}
	return *o.CustomCategoryThresholds.Get()
}

// GetCustomCategoryThresholdsOk returns a tuple with the CustomCategoryThresholds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModerationLLMV2Config) GetCustomCategoryThresholdsOk() (*ModerationLLMV2CategoryThresholds, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomCategoryThresholds.Get(), o.CustomCategoryThresholds.IsSet()
}

// HasCustomCategoryThresholds returns a boolean if a field has been set.
func (o *ModerationLLMV2Config) HasCustomCategoryThresholds() bool {
	if o != nil && o.CustomCategoryThresholds.IsSet() {
		return true
	}

	return false
}

// SetCustomCategoryThresholds gets a reference to the given NullableModerationLLMV2CategoryThresholds and assigns it to the CustomCategoryThresholds field.
func (o *ModerationLLMV2Config) SetCustomCategoryThresholds(v ModerationLLMV2CategoryThresholds) {
	o.CustomCategoryThresholds.Set(&v)
}
// SetCustomCategoryThresholdsNil sets the value for CustomCategoryThresholds to be an explicit nil
func (o *ModerationLLMV2Config) SetCustomCategoryThresholdsNil() {
	o.CustomCategoryThresholds.Set(nil)
}

// UnsetCustomCategoryThresholds ensures that no value is present for CustomCategoryThresholds, not even an explicit nil
func (o *ModerationLLMV2Config) UnsetCustomCategoryThresholds() {
	o.CustomCategoryThresholds.Unset()
}

// GetIgnoreOtherCategories returns the IgnoreOtherCategories field value if set, zero value otherwise.
func (o *ModerationLLMV2Config) GetIgnoreOtherCategories() bool {
	if o == nil || IsNil(o.IgnoreOtherCategories) {
		var ret bool
		return ret
	}
	return *o.IgnoreOtherCategories
}

// GetIgnoreOtherCategoriesOk returns a tuple with the IgnoreOtherCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModerationLLMV2Config) GetIgnoreOtherCategoriesOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreOtherCategories) {
		return nil, false
	}
	return o.IgnoreOtherCategories, true
}

// HasIgnoreOtherCategories returns a boolean if a field has been set.
func (o *ModerationLLMV2Config) HasIgnoreOtherCategories() bool {
	if o != nil && !IsNil(o.IgnoreOtherCategories) {
		return true
	}

	return false
}

// SetIgnoreOtherCategories gets a reference to the given bool and assigns it to the IgnoreOtherCategories field.
func (o *ModerationLLMV2Config) SetIgnoreOtherCategories(v bool) {
	o.IgnoreOtherCategories = &v
}

// GetModelName returns the ModelName field value if set, zero value otherwise.
func (o *ModerationLLMV2Config) GetModelName() string {
	if o == nil || IsNil(o.ModelName) {
		var ret string
		return ret
	}
	return *o.ModelName
}

// GetModelNameOk returns a tuple with the ModelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModerationLLMV2Config) GetModelNameOk() (*string, bool) {
	if o == nil || IsNil(o.ModelName) {
		return nil, false
	}
	return o.ModelName, true
}

// HasModelName returns a boolean if a field has been set.
func (o *ModerationLLMV2Config) HasModelName() bool {
	if o != nil && !IsNil(o.ModelName) {
		return true
	}

	return false
}

// SetModelName gets a reference to the given string and assigns it to the ModelName field.
func (o *ModerationLLMV2Config) SetModelName(v string) {
	o.ModelName = &v
}

func (o ModerationLLMV2Config) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModerationLLMV2Config) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if o.CustomCategoryThresholds.IsSet() {
		toSerialize["custom_category_thresholds"] = o.CustomCategoryThresholds.Get()
	}
	if !IsNil(o.IgnoreOtherCategories) {
		toSerialize["ignore_other_categories"] = o.IgnoreOtherCategories
	}
	if !IsNil(o.ModelName) {
		toSerialize["model_name"] = o.ModelName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModerationLLMV2Config) UnmarshalJSON(data []byte) (err error) {
	varModerationLLMV2Config := _ModerationLLMV2Config{}

	err = json.Unmarshal(data, &varModerationLLMV2Config)

	if err != nil {
		return err
	}

	*o = ModerationLLMV2Config(varModerationLLMV2Config)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "custom_category_thresholds")
		delete(additionalProperties, "ignore_other_categories")
		delete(additionalProperties, "model_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModerationLLMV2Config struct {
	value *ModerationLLMV2Config
	isSet bool
}

func (v NullableModerationLLMV2Config) Get() *ModerationLLMV2Config {
	return v.value
}

func (v *NullableModerationLLMV2Config) Set(val *ModerationLLMV2Config) {
	v.value = val
	v.isSet = true
}

func (v NullableModerationLLMV2Config) IsSet() bool {
	return v.isSet
}

func (v *NullableModerationLLMV2Config) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModerationLLMV2Config(val *ModerationLLMV2Config) *NullableModerationLLMV2Config {
	return &NullableModerationLLMV2Config{value: val, isSet: true}
}

func (v NullableModerationLLMV2Config) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModerationLLMV2Config) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
