/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the TokenLimitsByModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenLimitsByModel{}

// TokenLimitsByModel struct for TokenLimitsByModel
type TokenLimitsByModel struct {
	// Maximum tokens allowed per minute.
	TokensPerMinute int32 `json:"tokens_per_minute"`
	// Maximum tokens allowed per month.
	TokensPerMonth int32 `json:"tokens_per_month"`
	AdditionalProperties map[string]interface{}
}

type _TokenLimitsByModel TokenLimitsByModel

// NewTokenLimitsByModel instantiates a new TokenLimitsByModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenLimitsByModel(tokensPerMinute int32, tokensPerMonth int32) *TokenLimitsByModel {
	this := TokenLimitsByModel{}
	this.TokensPerMinute = tokensPerMinute
	this.TokensPerMonth = tokensPerMonth
	return &this
}

// NewTokenLimitsByModelWithDefaults instantiates a new TokenLimitsByModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenLimitsByModelWithDefaults() *TokenLimitsByModel {
	this := TokenLimitsByModel{}
	return &this
}

// GetTokensPerMinute returns the TokensPerMinute field value
func (o *TokenLimitsByModel) GetTokensPerMinute() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokensPerMinute
}

// GetTokensPerMinuteOk returns a tuple with the TokensPerMinute field value
// and a boolean to check if the value has been set.
func (o *TokenLimitsByModel) GetTokensPerMinuteOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokensPerMinute, true
}

// SetTokensPerMinute sets field value
func (o *TokenLimitsByModel) SetTokensPerMinute(v int32) {
	o.TokensPerMinute = v
}

// GetTokensPerMonth returns the TokensPerMonth field value
func (o *TokenLimitsByModel) GetTokensPerMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokensPerMonth
}

// GetTokensPerMonthOk returns a tuple with the TokensPerMonth field value
// and a boolean to check if the value has been set.
func (o *TokenLimitsByModel) GetTokensPerMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokensPerMonth, true
}

// SetTokensPerMonth sets field value
func (o *TokenLimitsByModel) SetTokensPerMonth(v int32) {
	o.TokensPerMonth = v
}

func (o TokenLimitsByModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenLimitsByModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tokens_per_minute"] = o.TokensPerMinute
	toSerialize["tokens_per_month"] = o.TokensPerMonth

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokenLimitsByModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tokens_per_minute",
		"tokens_per_month",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenLimitsByModel := _TokenLimitsByModel{}

	err = json.Unmarshal(data, &varTokenLimitsByModel)

	if err != nil {
		return err
	}

	*o = TokenLimitsByModel(varTokenLimitsByModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tokens_per_minute")
		delete(additionalProperties, "tokens_per_month")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokenLimitsByModel struct {
	value *TokenLimitsByModel
	isSet bool
}

func (v NullableTokenLimitsByModel) Get() *TokenLimitsByModel {
	return v.value
}

func (v *NullableTokenLimitsByModel) Set(val *TokenLimitsByModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenLimitsByModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenLimitsByModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenLimitsByModel(val *TokenLimitsByModel) *NullableTokenLimitsByModel {
	return &NullableTokenLimitsByModel{value: val, isSet: true}
}

func (v NullableTokenLimitsByModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenLimitsByModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
