/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ChatCompletionEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionEvent{}

// ChatCompletionEvent struct for ChatCompletionEvent
type ChatCompletionEvent struct {
	ChatTranscriptionEvents []ChatTranscriptionEvent `json:"chat_transcription_events"`
	CorrelationId string `json:"correlation_id"`
	CreatedAt time.Time `json:"created_at"`
	EnabledTools []map[string]interface{} `json:"enabled_tools"`
	EventId string `json:"event_id"`
	ExtraFields map[string]ExtraFieldsValue `json:"extra_fields"`
	NbInputTokens int32 `json:"nb_input_tokens"`
	NbMessages int32 `json:"nb_messages"`
	NbOutputTokens int32 `json:"nb_output_tokens"`
	RequestMessages []map[string]interface{} `json:"request_messages"`
	ResponseMessages []map[string]interface{} `json:"response_messages"`
	AdditionalProperties map[string]interface{}
}

type _ChatCompletionEvent ChatCompletionEvent

// NewChatCompletionEvent instantiates a new ChatCompletionEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionEvent(chatTranscriptionEvents []ChatTranscriptionEvent, correlationId string, createdAt time.Time, enabledTools []map[string]interface{}, eventId string, extraFields map[string]ExtraFieldsValue, nbInputTokens int32, nbMessages int32, nbOutputTokens int32, requestMessages []map[string]interface{}, responseMessages []map[string]interface{}) *ChatCompletionEvent {
	this := ChatCompletionEvent{}
	this.ChatTranscriptionEvents = chatTranscriptionEvents
	this.CorrelationId = correlationId
	this.CreatedAt = createdAt
	this.EnabledTools = enabledTools
	this.EventId = eventId
	this.ExtraFields = extraFields
	this.NbInputTokens = nbInputTokens
	this.NbMessages = nbMessages
	this.NbOutputTokens = nbOutputTokens
	this.RequestMessages = requestMessages
	this.ResponseMessages = responseMessages
	return &this
}

// NewChatCompletionEventWithDefaults instantiates a new ChatCompletionEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionEventWithDefaults() *ChatCompletionEvent {
	this := ChatCompletionEvent{}
	return &this
}

// GetChatTranscriptionEvents returns the ChatTranscriptionEvents field value
func (o *ChatCompletionEvent) GetChatTranscriptionEvents() []ChatTranscriptionEvent {
	if o == nil {
		var ret []ChatTranscriptionEvent
		return ret
	}

	return o.ChatTranscriptionEvents
}

// GetChatTranscriptionEventsOk returns a tuple with the ChatTranscriptionEvents field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetChatTranscriptionEventsOk() ([]ChatTranscriptionEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChatTranscriptionEvents, true
}

// SetChatTranscriptionEvents sets field value
func (o *ChatCompletionEvent) SetChatTranscriptionEvents(v []ChatTranscriptionEvent) {
	o.ChatTranscriptionEvents = v
}

// GetCorrelationId returns the CorrelationId field value
func (o *ChatCompletionEvent) GetCorrelationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CorrelationId
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetCorrelationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorrelationId, true
}

// SetCorrelationId sets field value
func (o *ChatCompletionEvent) SetCorrelationId(v string) {
	o.CorrelationId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ChatCompletionEvent) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ChatCompletionEvent) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEnabledTools returns the EnabledTools field value
func (o *ChatCompletionEvent) GetEnabledTools() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.EnabledTools
}

// GetEnabledToolsOk returns a tuple with the EnabledTools field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetEnabledToolsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnabledTools, true
}

// SetEnabledTools sets field value
func (o *ChatCompletionEvent) SetEnabledTools(v []map[string]interface{}) {
	o.EnabledTools = v
}

// GetEventId returns the EventId field value
func (o *ChatCompletionEvent) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *ChatCompletionEvent) SetEventId(v string) {
	o.EventId = v
}

// GetExtraFields returns the ExtraFields field value
func (o *ChatCompletionEvent) GetExtraFields() map[string]ExtraFieldsValue {
	if o == nil {
		var ret map[string]ExtraFieldsValue
		return ret
	}

	return o.ExtraFields
}

// GetExtraFieldsOk returns a tuple with the ExtraFields field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetExtraFieldsOk() (map[string]ExtraFieldsValue, bool) {
	if o == nil {
		return map[string]ExtraFieldsValue{}, false
	}
	return o.ExtraFields, true
}

// SetExtraFields sets field value
func (o *ChatCompletionEvent) SetExtraFields(v map[string]ExtraFieldsValue) {
	o.ExtraFields = v
}

// GetNbInputTokens returns the NbInputTokens field value
func (o *ChatCompletionEvent) GetNbInputTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NbInputTokens
}

// GetNbInputTokensOk returns a tuple with the NbInputTokens field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetNbInputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NbInputTokens, true
}

// SetNbInputTokens sets field value
func (o *ChatCompletionEvent) SetNbInputTokens(v int32) {
	o.NbInputTokens = v
}

// GetNbMessages returns the NbMessages field value
func (o *ChatCompletionEvent) GetNbMessages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NbMessages
}

// GetNbMessagesOk returns a tuple with the NbMessages field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetNbMessagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NbMessages, true
}

// SetNbMessages sets field value
func (o *ChatCompletionEvent) SetNbMessages(v int32) {
	o.NbMessages = v
}

// GetNbOutputTokens returns the NbOutputTokens field value
func (o *ChatCompletionEvent) GetNbOutputTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NbOutputTokens
}

// GetNbOutputTokensOk returns a tuple with the NbOutputTokens field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetNbOutputTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NbOutputTokens, true
}

// SetNbOutputTokens sets field value
func (o *ChatCompletionEvent) SetNbOutputTokens(v int32) {
	o.NbOutputTokens = v
}

// GetRequestMessages returns the RequestMessages field value
func (o *ChatCompletionEvent) GetRequestMessages() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.RequestMessages
}

// GetRequestMessagesOk returns a tuple with the RequestMessages field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetRequestMessagesOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestMessages, true
}

// SetRequestMessages sets field value
func (o *ChatCompletionEvent) SetRequestMessages(v []map[string]interface{}) {
	o.RequestMessages = v
}

// GetResponseMessages returns the ResponseMessages field value
func (o *ChatCompletionEvent) GetResponseMessages() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.ResponseMessages
}

// GetResponseMessagesOk returns a tuple with the ResponseMessages field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionEvent) GetResponseMessagesOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseMessages, true
}

// SetResponseMessages sets field value
func (o *ChatCompletionEvent) SetResponseMessages(v []map[string]interface{}) {
	o.ResponseMessages = v
}

func (o ChatCompletionEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chat_transcription_events"] = o.ChatTranscriptionEvents
	toSerialize["correlation_id"] = o.CorrelationId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["enabled_tools"] = o.EnabledTools
	toSerialize["event_id"] = o.EventId
	toSerialize["extra_fields"] = o.ExtraFields
	toSerialize["nb_input_tokens"] = o.NbInputTokens
	toSerialize["nb_messages"] = o.NbMessages
	toSerialize["nb_output_tokens"] = o.NbOutputTokens
	toSerialize["request_messages"] = o.RequestMessages
	toSerialize["response_messages"] = o.ResponseMessages

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChatCompletionEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chat_transcription_events",
		"correlation_id",
		"created_at",
		"enabled_tools",
		"event_id",
		"extra_fields",
		"nb_input_tokens",
		"nb_messages",
		"nb_output_tokens",
		"request_messages",
		"response_messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatCompletionEvent := _ChatCompletionEvent{}

	err = json.Unmarshal(data, &varChatCompletionEvent)

	if err != nil {
		return err
	}

	*o = ChatCompletionEvent(varChatCompletionEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "chat_transcription_events")
		delete(additionalProperties, "correlation_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "enabled_tools")
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "extra_fields")
		delete(additionalProperties, "nb_input_tokens")
		delete(additionalProperties, "nb_messages")
		delete(additionalProperties, "nb_output_tokens")
		delete(additionalProperties, "request_messages")
		delete(additionalProperties, "response_messages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChatCompletionEvent struct {
	value *ChatCompletionEvent
	isSet bool
}

func (v NullableChatCompletionEvent) Get() *ChatCompletionEvent {
	return v.value
}

func (v *NullableChatCompletionEvent) Set(val *ChatCompletionEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionEvent(val *ChatCompletionEvent) *NullableChatCompletionEvent {
	return &NullableChatCompletionEvent{value: val, isSet: true}
}

func (v NullableChatCompletionEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
