/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the RegisterSearchIndexResponseIndex type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterSearchIndexResponseIndex{}

// RegisterSearchIndexResponseIndex struct for RegisterSearchIndexResponseIndex
type RegisterSearchIndexResponseIndex struct {
	Id string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _RegisterSearchIndexResponseIndex RegisterSearchIndexResponseIndex

// NewRegisterSearchIndexResponseIndex instantiates a new RegisterSearchIndexResponseIndex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterSearchIndexResponseIndex(id string) *RegisterSearchIndexResponseIndex {
	this := RegisterSearchIndexResponseIndex{}
	this.Id = id
	return &this
}

// NewRegisterSearchIndexResponseIndexWithDefaults instantiates a new RegisterSearchIndexResponseIndex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterSearchIndexResponseIndexWithDefaults() *RegisterSearchIndexResponseIndex {
	this := RegisterSearchIndexResponseIndex{}
	return &this
}

// GetId returns the Id field value
func (o *RegisterSearchIndexResponseIndex) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegisterSearchIndexResponseIndex) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegisterSearchIndexResponseIndex) SetId(v string) {
	o.Id = v
}

func (o RegisterSearchIndexResponseIndex) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterSearchIndexResponseIndex) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegisterSearchIndexResponseIndex) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterSearchIndexResponseIndex := _RegisterSearchIndexResponseIndex{}

	err = json.Unmarshal(data, &varRegisterSearchIndexResponseIndex)

	if err != nil {
		return err
	}

	*o = RegisterSearchIndexResponseIndex(varRegisterSearchIndexResponseIndex)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegisterSearchIndexResponseIndex struct {
	value *RegisterSearchIndexResponseIndex
	isSet bool
}

func (v NullableRegisterSearchIndexResponseIndex) Get() *RegisterSearchIndexResponseIndex {
	return v.value
}

func (v *NullableRegisterSearchIndexResponseIndex) Set(val *RegisterSearchIndexResponseIndex) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterSearchIndexResponseIndex) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterSearchIndexResponseIndex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterSearchIndexResponseIndex(val *RegisterSearchIndexResponseIndex) *NullableRegisterSearchIndexResponseIndex {
	return &NullableRegisterSearchIndexResponseIndex{value: val, isSet: true}
}

func (v NullableRegisterSearchIndexResponseIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterSearchIndexResponseIndex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
