/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)


// Role Deprecated legacy single role value, kept for backward compatibility. Mutually exclusive with 'role_name'.
type Role struct {
	StaticOrganizationRoles *StaticOrganizationRoles
	UserRole *UserRole
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Role) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into StaticOrganizationRoles
	err = json.Unmarshal(data, &dst.StaticOrganizationRoles);
	if err == nil {
		jsonStaticOrganizationRoles, _ := json.Marshal(dst.StaticOrganizationRoles)
		if string(jsonStaticOrganizationRoles) == "{}" { // empty struct
			dst.StaticOrganizationRoles = nil
		} else {
			return nil // data stored in dst.StaticOrganizationRoles, return on the first match
		}
	} else {
		dst.StaticOrganizationRoles = nil
	}

	// try to unmarshal JSON data into UserRole
	err = json.Unmarshal(data, &dst.UserRole);
	if err == nil {
		jsonUserRole, _ := json.Marshal(dst.UserRole)
		if string(jsonUserRole) == "{}" { // empty struct
			dst.UserRole = nil
		} else {
			return nil // data stored in dst.UserRole, return on the first match
		}
	} else {
		dst.UserRole = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Role)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Role) MarshalJSON() ([]byte, error) {
	if src.StaticOrganizationRoles != nil {
		return json.Marshal(&src.StaticOrganizationRoles)
	}

	if src.UserRole != nil {
		return json.Marshal(&src.UserRole)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableRole struct {
	value *Role
	isSet bool
}

func (v NullableRole) Get() *Role {
	return v.value
}

func (v *NullableRole) Set(val *Role) {
	v.value = val
	v.isSet = true
}

func (v NullableRole) IsSet() bool {
	return v.isSet
}

func (v *NullableRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRole(val *Role) *NullableRole {
	return &NullableRole{value: val, isSet: true}
}

func (v NullableRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
