/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomTaskStartedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomTaskStartedResponse{}

// CustomTaskStartedResponse Emitted when a custom task begins execution.  Custom tasks represent user-defined units of work within a workflow, such as LLM calls, API requests, or data processing steps.
type CustomTaskStartedResponse struct {
	// Event-specific attributes.
	Attributes CustomTaskStartedAttributesResponse `json:"attributes"`
	// Unique identifier for this event instance.
	EventId string `json:"event_id"`
	// Unix timestamp in nanoseconds when the event was created.
	EventTimestamp int32 `json:"event_timestamp"`
	// Event type discriminator.
	EventType string `json:"event_type"`
	// Execution ID of the parent workflow that initiated this execution. If this is a root workflow, this field is not set.
	ParentWorkflowExecId NullableString `json:"parent_workflow_exec_id"`
	// Execution ID of the root workflow that initiated this execution chain.
	RootWorkflowExecId string `json:"root_workflow_exec_id"`
	// Execution ID of the workflow that emitted this event.
	WorkflowExecId string `json:"workflow_exec_id"`
	// The registered name of the workflow that emitted this event.
	WorkflowName string `json:"workflow_name"`
	// Run ID of the workflow execution. Changes on continue-as-new while workflow_exec_id stays the same.
	WorkflowRunId string `json:"workflow_run_id"`
	AdditionalProperties map[string]interface{}
}

type _CustomTaskStartedResponse CustomTaskStartedResponse

// NewCustomTaskStartedResponse instantiates a new CustomTaskStartedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomTaskStartedResponse(attributes CustomTaskStartedAttributesResponse, eventId string, eventTimestamp int32, eventType string, parentWorkflowExecId NullableString, rootWorkflowExecId string, workflowExecId string, workflowName string, workflowRunId string) *CustomTaskStartedResponse {
	this := CustomTaskStartedResponse{}
	this.Attributes = attributes
	this.EventId = eventId
	this.EventTimestamp = eventTimestamp
	this.EventType = eventType
	this.ParentWorkflowExecId = parentWorkflowExecId
	this.RootWorkflowExecId = rootWorkflowExecId
	this.WorkflowExecId = workflowExecId
	this.WorkflowName = workflowName
	this.WorkflowRunId = workflowRunId
	return &this
}

// NewCustomTaskStartedResponseWithDefaults instantiates a new CustomTaskStartedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomTaskStartedResponseWithDefaults() *CustomTaskStartedResponse {
	this := CustomTaskStartedResponse{}
	var eventType string = "CUSTOM_TASK_STARTED"
	this.EventType = eventType
	return &this
}

// GetAttributes returns the Attributes field value
func (o *CustomTaskStartedResponse) GetAttributes() CustomTaskStartedAttributesResponse {
	if o == nil {
		var ret CustomTaskStartedAttributesResponse
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetAttributesOk() (*CustomTaskStartedAttributesResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CustomTaskStartedResponse) SetAttributes(v CustomTaskStartedAttributesResponse) {
	o.Attributes = v
}

// GetEventId returns the EventId field value
func (o *CustomTaskStartedResponse) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *CustomTaskStartedResponse) SetEventId(v string) {
	o.EventId = v
}

// GetEventTimestamp returns the EventTimestamp field value
func (o *CustomTaskStartedResponse) GetEventTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventTimestamp
}

// GetEventTimestampOk returns a tuple with the EventTimestamp field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetEventTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventTimestamp, true
}

// SetEventTimestamp sets field value
func (o *CustomTaskStartedResponse) SetEventTimestamp(v int32) {
	o.EventTimestamp = v
}

// GetEventType returns the EventType field value
func (o *CustomTaskStartedResponse) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *CustomTaskStartedResponse) SetEventType(v string) {
	o.EventType = v
}

// GetParentWorkflowExecId returns the ParentWorkflowExecId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomTaskStartedResponse) GetParentWorkflowExecId() string {
	if o == nil || o.ParentWorkflowExecId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ParentWorkflowExecId.Get()
}

// GetParentWorkflowExecIdOk returns a tuple with the ParentWorkflowExecId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomTaskStartedResponse) GetParentWorkflowExecIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentWorkflowExecId.Get(), o.ParentWorkflowExecId.IsSet()
}

// SetParentWorkflowExecId sets field value
func (o *CustomTaskStartedResponse) SetParentWorkflowExecId(v string) {
	o.ParentWorkflowExecId.Set(&v)
}

// GetRootWorkflowExecId returns the RootWorkflowExecId field value
func (o *CustomTaskStartedResponse) GetRootWorkflowExecId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootWorkflowExecId
}

// GetRootWorkflowExecIdOk returns a tuple with the RootWorkflowExecId field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetRootWorkflowExecIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootWorkflowExecId, true
}

// SetRootWorkflowExecId sets field value
func (o *CustomTaskStartedResponse) SetRootWorkflowExecId(v string) {
	o.RootWorkflowExecId = v
}

// GetWorkflowExecId returns the WorkflowExecId field value
func (o *CustomTaskStartedResponse) GetWorkflowExecId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowExecId
}

// GetWorkflowExecIdOk returns a tuple with the WorkflowExecId field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetWorkflowExecIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowExecId, true
}

// SetWorkflowExecId sets field value
func (o *CustomTaskStartedResponse) SetWorkflowExecId(v string) {
	o.WorkflowExecId = v
}

// GetWorkflowName returns the WorkflowName field value
func (o *CustomTaskStartedResponse) GetWorkflowName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowName
}

// GetWorkflowNameOk returns a tuple with the WorkflowName field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetWorkflowNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowName, true
}

// SetWorkflowName sets field value
func (o *CustomTaskStartedResponse) SetWorkflowName(v string) {
	o.WorkflowName = v
}

// GetWorkflowRunId returns the WorkflowRunId field value
func (o *CustomTaskStartedResponse) GetWorkflowRunId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowRunId
}

// GetWorkflowRunIdOk returns a tuple with the WorkflowRunId field value
// and a boolean to check if the value has been set.
func (o *CustomTaskStartedResponse) GetWorkflowRunIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowRunId, true
}

// SetWorkflowRunId sets field value
func (o *CustomTaskStartedResponse) SetWorkflowRunId(v string) {
	o.WorkflowRunId = v
}

func (o CustomTaskStartedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomTaskStartedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["event_id"] = o.EventId
	toSerialize["event_timestamp"] = o.EventTimestamp
	toSerialize["event_type"] = o.EventType
	toSerialize["parent_workflow_exec_id"] = o.ParentWorkflowExecId.Get()
	toSerialize["root_workflow_exec_id"] = o.RootWorkflowExecId
	toSerialize["workflow_exec_id"] = o.WorkflowExecId
	toSerialize["workflow_name"] = o.WorkflowName
	toSerialize["workflow_run_id"] = o.WorkflowRunId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomTaskStartedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"event_id",
		"event_timestamp",
		"event_type",
		"parent_workflow_exec_id",
		"root_workflow_exec_id",
		"workflow_exec_id",
		"workflow_name",
		"workflow_run_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomTaskStartedResponse := _CustomTaskStartedResponse{}

	err = json.Unmarshal(data, &varCustomTaskStartedResponse)

	if err != nil {
		return err
	}

	*o = CustomTaskStartedResponse(varCustomTaskStartedResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "event_timestamp")
		delete(additionalProperties, "event_type")
		delete(additionalProperties, "parent_workflow_exec_id")
		delete(additionalProperties, "root_workflow_exec_id")
		delete(additionalProperties, "workflow_exec_id")
		delete(additionalProperties, "workflow_name")
		delete(additionalProperties, "workflow_run_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomTaskStartedResponse struct {
	value *CustomTaskStartedResponse
	isSet bool
}

func (v NullableCustomTaskStartedResponse) Get() *CustomTaskStartedResponse {
	return v.value
}

func (v *NullableCustomTaskStartedResponse) Set(val *CustomTaskStartedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomTaskStartedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomTaskStartedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomTaskStartedResponse(val *CustomTaskStartedResponse) *NullableCustomTaskStartedResponse {
	return &NullableCustomTaskStartedResponse{value: val, isSet: true}
}

func (v NullableCustomTaskStartedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomTaskStartedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
