/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// FileVisibility the model 'FileVisibility'
type FileVisibility string

// List of FileVisibility
const (
	FILEVISIBILITY_WORKSPACE FileVisibility = "workspace"
	FILEVISIBILITY_USER FileVisibility = "user"
)

// All allowed values of FileVisibility enum
var AllowedFileVisibilityEnumValues = []FileVisibility{
	"workspace",
	"user",
}

func (v *FileVisibility) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FileVisibility(value)
	for _, existing := range AllowedFileVisibilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FileVisibility", value)
}

// NewFileVisibilityFromValue returns a pointer to a valid FileVisibility
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFileVisibilityFromValue(v string) (*FileVisibility, error) {
	ev := FileVisibility(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FileVisibility: valid values are %v", v, AllowedFileVisibilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FileVisibility) IsValid() bool {
	for _, existing := range AllowedFileVisibilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FileVisibility value
func (v FileVisibility) Ptr() *FileVisibility {
	return &v
}

type NullableFileVisibility struct {
	value *FileVisibility
	isSet bool
}

func (v NullableFileVisibility) Get() *FileVisibility {
	return v.value
}

func (v *NullableFileVisibility) Set(val *FileVisibility) {
	v.value = val
	v.isSet = true
}

func (v NullableFileVisibility) IsSet() bool {
	return v.isSet
}

func (v *NullableFileVisibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileVisibility(val *FileVisibility) *NullableFileVisibility {
	return &NullableFileVisibility{value: val, isSet: true}
}

func (v NullableFileVisibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileVisibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
