/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the WorkflowExecutionCompletedAttributesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowExecutionCompletedAttributesResponse{}

// WorkflowExecutionCompletedAttributesResponse Attributes for workflow execution completed events.
type WorkflowExecutionCompletedAttributesResponse struct {
	// The final result returned by the workflow.
	Result JSONPayloadResponse `json:"result"`
	// Unique identifier for the task within the workflow execution.
	TaskId string `json:"task_id"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowExecutionCompletedAttributesResponse WorkflowExecutionCompletedAttributesResponse

// NewWorkflowExecutionCompletedAttributesResponse instantiates a new WorkflowExecutionCompletedAttributesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowExecutionCompletedAttributesResponse(result JSONPayloadResponse, taskId string) *WorkflowExecutionCompletedAttributesResponse {
	this := WorkflowExecutionCompletedAttributesResponse{}
	this.Result = result
	this.TaskId = taskId
	return &this
}

// NewWorkflowExecutionCompletedAttributesResponseWithDefaults instantiates a new WorkflowExecutionCompletedAttributesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowExecutionCompletedAttributesResponseWithDefaults() *WorkflowExecutionCompletedAttributesResponse {
	this := WorkflowExecutionCompletedAttributesResponse{}
	return &this
}

// GetResult returns the Result field value
func (o *WorkflowExecutionCompletedAttributesResponse) GetResult() JSONPayloadResponse {
	if o == nil {
		var ret JSONPayloadResponse
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionCompletedAttributesResponse) GetResultOk() (*JSONPayloadResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *WorkflowExecutionCompletedAttributesResponse) SetResult(v JSONPayloadResponse) {
	o.Result = v
}

// GetTaskId returns the TaskId field value
func (o *WorkflowExecutionCompletedAttributesResponse) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *WorkflowExecutionCompletedAttributesResponse) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *WorkflowExecutionCompletedAttributesResponse) SetTaskId(v string) {
	o.TaskId = v
}

func (o WorkflowExecutionCompletedAttributesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowExecutionCompletedAttributesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["task_id"] = o.TaskId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowExecutionCompletedAttributesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"task_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowExecutionCompletedAttributesResponse := _WorkflowExecutionCompletedAttributesResponse{}

	err = json.Unmarshal(data, &varWorkflowExecutionCompletedAttributesResponse)

	if err != nil {
		return err
	}

	*o = WorkflowExecutionCompletedAttributesResponse(varWorkflowExecutionCompletedAttributesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		delete(additionalProperties, "task_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowExecutionCompletedAttributesResponse struct {
	value *WorkflowExecutionCompletedAttributesResponse
	isSet bool
}

func (v NullableWorkflowExecutionCompletedAttributesResponse) Get() *WorkflowExecutionCompletedAttributesResponse {
	return v.value
}

func (v *NullableWorkflowExecutionCompletedAttributesResponse) Set(val *WorkflowExecutionCompletedAttributesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowExecutionCompletedAttributesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowExecutionCompletedAttributesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowExecutionCompletedAttributesResponse(val *WorkflowExecutionCompletedAttributesResponse) *NullableWorkflowExecutionCompletedAttributesResponse {
	return &NullableWorkflowExecutionCompletedAttributesResponse{value: val, isSet: true}
}

func (v NullableWorkflowExecutionCompletedAttributesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowExecutionCompletedAttributesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
