/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)


// RawRole Deprecated single organization role. Use 'raw_roles' instead.
type RawRole struct {
	StaticOrganizationRoles *StaticOrganizationRoles
	UserRole *UserRole
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RawRole) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into StaticOrganizationRoles
	err = json.Unmarshal(data, &dst.StaticOrganizationRoles);
	if err == nil {
		jsonStaticOrganizationRoles, _ := json.Marshal(dst.StaticOrganizationRoles)
		if string(jsonStaticOrganizationRoles) == "{}" { // empty struct
			dst.StaticOrganizationRoles = nil
		} else {
			return nil // data stored in dst.StaticOrganizationRoles, return on the first match
		}
	} else {
		dst.StaticOrganizationRoles = nil
	}

	// try to unmarshal JSON data into UserRole
	err = json.Unmarshal(data, &dst.UserRole);
	if err == nil {
		jsonUserRole, _ := json.Marshal(dst.UserRole)
		if string(jsonUserRole) == "{}" { // empty struct
			dst.UserRole = nil
		} else {
			return nil // data stored in dst.UserRole, return on the first match
		}
	} else {
		dst.UserRole = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(RawRole)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RawRole) MarshalJSON() ([]byte, error) {
	if src.StaticOrganizationRoles != nil {
		return json.Marshal(&src.StaticOrganizationRoles)
	}

	if src.UserRole != nil {
		return json.Marshal(&src.UserRole)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableRawRole struct {
	value *RawRole
	isSet bool
}

func (v NullableRawRole) Get() *RawRole {
	return v.value
}

func (v *NullableRawRole) Set(val *RawRole) {
	v.value = val
	v.isSet = true
}

func (v NullableRawRole) IsSet() bool {
	return v.isSet
}

func (v *NullableRawRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRawRole(val *RawRole) *NullableRawRole {
	return &NullableRawRole{value: val, isSet: true}
}

func (v NullableRawRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRawRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
