/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
)

// checks if the ListSkillVersionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSkillVersionsResponse{}

// ListSkillVersionsResponse struct for ListSkillVersionsResponse
type ListSkillVersionsResponse struct {
	Data []SkillVersion `json:"data,omitempty"`
}

// NewListSkillVersionsResponse instantiates a new ListSkillVersionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSkillVersionsResponse() *ListSkillVersionsResponse {
	this := ListSkillVersionsResponse{}
	return &this
}

// NewListSkillVersionsResponseWithDefaults instantiates a new ListSkillVersionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSkillVersionsResponseWithDefaults() *ListSkillVersionsResponse {
	this := ListSkillVersionsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListSkillVersionsResponse) GetData() []SkillVersion {
	if o == nil || IsNil(o.Data) {
		var ret []SkillVersion
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSkillVersionsResponse) GetDataOk() ([]SkillVersion, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListSkillVersionsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SkillVersion and assigns it to the Data field.
func (o *ListSkillVersionsResponse) SetData(v []SkillVersion) {
	o.Data = v
}

func (o ListSkillVersionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSkillVersionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListSkillVersionsResponse struct {
	value *ListSkillVersionsResponse
	isSet bool
}

func (v NullableListSkillVersionsResponse) Get() *ListSkillVersionsResponse {
	return v.value
}

func (v *NullableListSkillVersionsResponse) Set(val *ListSkillVersionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListSkillVersionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListSkillVersionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSkillVersionsResponse(val *ListSkillVersionsResponse) *NullableListSkillVersionsResponse {
	return &NullableListSkillVersionsResponse{value: val, isSet: true}
}

func (v NullableListSkillVersionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSkillVersionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
