/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the TempoTraceAttributeArrayValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TempoTraceAttributeArrayValue{}

// TempoTraceAttributeArrayValue struct for TempoTraceAttributeArrayValue
type TempoTraceAttributeArrayValue struct {
	// The array value of the attribute
	ArrayValue TempoTraceAttributeArrayContainer `json:"arrayValue"`
	AdditionalProperties map[string]interface{}
}

type _TempoTraceAttributeArrayValue TempoTraceAttributeArrayValue

// NewTempoTraceAttributeArrayValue instantiates a new TempoTraceAttributeArrayValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTempoTraceAttributeArrayValue(arrayValue TempoTraceAttributeArrayContainer) *TempoTraceAttributeArrayValue {
	this := TempoTraceAttributeArrayValue{}
	this.ArrayValue = arrayValue
	return &this
}

// NewTempoTraceAttributeArrayValueWithDefaults instantiates a new TempoTraceAttributeArrayValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTempoTraceAttributeArrayValueWithDefaults() *TempoTraceAttributeArrayValue {
	this := TempoTraceAttributeArrayValue{}
	return &this
}

// GetArrayValue returns the ArrayValue field value
func (o *TempoTraceAttributeArrayValue) GetArrayValue() TempoTraceAttributeArrayContainer {
	if o == nil {
		var ret TempoTraceAttributeArrayContainer
		return ret
	}

	return o.ArrayValue
}

// GetArrayValueOk returns a tuple with the ArrayValue field value
// and a boolean to check if the value has been set.
func (o *TempoTraceAttributeArrayValue) GetArrayValueOk() (*TempoTraceAttributeArrayContainer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArrayValue, true
}

// SetArrayValue sets field value
func (o *TempoTraceAttributeArrayValue) SetArrayValue(v TempoTraceAttributeArrayContainer) {
	o.ArrayValue = v
}

func (o TempoTraceAttributeArrayValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TempoTraceAttributeArrayValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["arrayValue"] = o.ArrayValue

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TempoTraceAttributeArrayValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"arrayValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTempoTraceAttributeArrayValue := _TempoTraceAttributeArrayValue{}

	err = json.Unmarshal(data, &varTempoTraceAttributeArrayValue)

	if err != nil {
		return err
	}

	*o = TempoTraceAttributeArrayValue(varTempoTraceAttributeArrayValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "arrayValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTempoTraceAttributeArrayValue struct {
	value *TempoTraceAttributeArrayValue
	isSet bool
}

func (v NullableTempoTraceAttributeArrayValue) Get() *TempoTraceAttributeArrayValue {
	return v.value
}

func (v *NullableTempoTraceAttributeArrayValue) Set(val *TempoTraceAttributeArrayValue) {
	v.value = val
	v.isSet = true
}

func (v NullableTempoTraceAttributeArrayValue) IsSet() bool {
	return v.isSet
}

func (v *NullableTempoTraceAttributeArrayValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTempoTraceAttributeArrayValue(val *TempoTraceAttributeArrayValue) *NullableTempoTraceAttributeArrayValue {
	return &NullableTempoTraceAttributeArrayValue{value: val, isSet: true}
}

func (v NullableTempoTraceAttributeArrayValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTempoTraceAttributeArrayValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
