/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
)

// checks if the ActionUnavailableRotateUnavailableReason type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionUnavailableRotateUnavailableReason{}

// ActionUnavailableRotateUnavailableReason struct for ActionUnavailableRotateUnavailableReason
type ActionUnavailableRotateUnavailableReason struct {
	Reason NullableRotateUnavailableReason `json:"reason,omitempty"`
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ActionUnavailableRotateUnavailableReason ActionUnavailableRotateUnavailableReason

// NewActionUnavailableRotateUnavailableReason instantiates a new ActionUnavailableRotateUnavailableReason object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionUnavailableRotateUnavailableReason() *ActionUnavailableRotateUnavailableReason {
	this := ActionUnavailableRotateUnavailableReason{}
	var status string = "unavailable"
	this.Status = &status
	return &this
}

// NewActionUnavailableRotateUnavailableReasonWithDefaults instantiates a new ActionUnavailableRotateUnavailableReason object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionUnavailableRotateUnavailableReasonWithDefaults() *ActionUnavailableRotateUnavailableReason {
	this := ActionUnavailableRotateUnavailableReason{}
	var status string = "unavailable"
	this.Status = &status
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActionUnavailableRotateUnavailableReason) GetReason() RotateUnavailableReason {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret RotateUnavailableReason
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionUnavailableRotateUnavailableReason) GetReasonOk() (*RotateUnavailableReason, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *ActionUnavailableRotateUnavailableReason) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableRotateUnavailableReason and assigns it to the Reason field.
func (o *ActionUnavailableRotateUnavailableReason) SetReason(v RotateUnavailableReason) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *ActionUnavailableRotateUnavailableReason) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *ActionUnavailableRotateUnavailableReason) UnsetReason() {
	o.Reason.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ActionUnavailableRotateUnavailableReason) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionUnavailableRotateUnavailableReason) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ActionUnavailableRotateUnavailableReason) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ActionUnavailableRotateUnavailableReason) SetStatus(v string) {
	o.Status = &v
}

func (o ActionUnavailableRotateUnavailableReason) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionUnavailableRotateUnavailableReason) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionUnavailableRotateUnavailableReason) UnmarshalJSON(data []byte) (err error) {
	varActionUnavailableRotateUnavailableReason := _ActionUnavailableRotateUnavailableReason{}

	err = json.Unmarshal(data, &varActionUnavailableRotateUnavailableReason)

	if err != nil {
		return err
	}

	*o = ActionUnavailableRotateUnavailableReason(varActionUnavailableRotateUnavailableReason)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "reason")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionUnavailableRotateUnavailableReason struct {
	value *ActionUnavailableRotateUnavailableReason
	isSet bool
}

func (v NullableActionUnavailableRotateUnavailableReason) Get() *ActionUnavailableRotateUnavailableReason {
	return v.value
}

func (v *NullableActionUnavailableRotateUnavailableReason) Set(val *ActionUnavailableRotateUnavailableReason) {
	v.value = val
	v.isSet = true
}

func (v NullableActionUnavailableRotateUnavailableReason) IsSet() bool {
	return v.isSet
}

func (v *NullableActionUnavailableRotateUnavailableReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionUnavailableRotateUnavailableReason(val *ActionUnavailableRotateUnavailableReason) *NullableActionUnavailableRotateUnavailableReason {
	return &NullableActionUnavailableRotateUnavailableReason{value: val, isSet: true}
}

func (v NullableActionUnavailableRotateUnavailableReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionUnavailableRotateUnavailableReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
