/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
)

// checks if the ConversationAppendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConversationAppendRequest{}

// ConversationAppendRequest struct for ConversationAppendRequest
type ConversationAppendRequest struct {
	// Completion arguments that will be used to generate assistant responses. Can be overridden at each message request.
	CompletionArgs *CompletionArgs `json:"completion_args,omitempty"`
	HandoffExecution *string `json:"handoff_execution,omitempty"`
	Inputs *ConversationInputs `json:"inputs,omitempty"`
	// Whether to store the results into our servers or not.
	Store *bool `json:"store,omitempty"`
	Stream *bool `json:"stream,omitempty"`
	ToolConfirmations []ToolCallConfirmation `json:"tool_confirmations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConversationAppendRequest ConversationAppendRequest

// NewConversationAppendRequest instantiates a new ConversationAppendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConversationAppendRequest() *ConversationAppendRequest {
	this := ConversationAppendRequest{}
	var handoffExecution string = "server"
	this.HandoffExecution = &handoffExecution
	var store bool = true
	this.Store = &store
	var stream bool = false
	this.Stream = &stream
	return &this
}

// NewConversationAppendRequestWithDefaults instantiates a new ConversationAppendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConversationAppendRequestWithDefaults() *ConversationAppendRequest {
	this := ConversationAppendRequest{}
	var handoffExecution string = "server"
	this.HandoffExecution = &handoffExecution
	var store bool = true
	this.Store = &store
	var stream bool = false
	this.Stream = &stream
	return &this
}

// GetCompletionArgs returns the CompletionArgs field value if set, zero value otherwise.
func (o *ConversationAppendRequest) GetCompletionArgs() CompletionArgs {
	if o == nil || IsNil(o.CompletionArgs) {
		var ret CompletionArgs
		return ret
	}
	return *o.CompletionArgs
}

// GetCompletionArgsOk returns a tuple with the CompletionArgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationAppendRequest) GetCompletionArgsOk() (*CompletionArgs, bool) {
	if o == nil || IsNil(o.CompletionArgs) {
		return nil, false
	}
	return o.CompletionArgs, true
}

// HasCompletionArgs returns a boolean if a field has been set.
func (o *ConversationAppendRequest) HasCompletionArgs() bool {
	if o != nil && !IsNil(o.CompletionArgs) {
		return true
	}

	return false
}

// SetCompletionArgs gets a reference to the given CompletionArgs and assigns it to the CompletionArgs field.
func (o *ConversationAppendRequest) SetCompletionArgs(v CompletionArgs) {
	o.CompletionArgs = &v
}

// GetHandoffExecution returns the HandoffExecution field value if set, zero value otherwise.
func (o *ConversationAppendRequest) GetHandoffExecution() string {
	if o == nil || IsNil(o.HandoffExecution) {
		var ret string
		return ret
	}
	return *o.HandoffExecution
}

// GetHandoffExecutionOk returns a tuple with the HandoffExecution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationAppendRequest) GetHandoffExecutionOk() (*string, bool) {
	if o == nil || IsNil(o.HandoffExecution) {
		return nil, false
	}
	return o.HandoffExecution, true
}

// HasHandoffExecution returns a boolean if a field has been set.
func (o *ConversationAppendRequest) HasHandoffExecution() bool {
	if o != nil && !IsNil(o.HandoffExecution) {
		return true
	}

	return false
}

// SetHandoffExecution gets a reference to the given string and assigns it to the HandoffExecution field.
func (o *ConversationAppendRequest) SetHandoffExecution(v string) {
	o.HandoffExecution = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *ConversationAppendRequest) GetInputs() ConversationInputs {
	if o == nil || IsNil(o.Inputs) {
		var ret ConversationInputs
		return ret
	}
	return *o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationAppendRequest) GetInputsOk() (*ConversationInputs, bool) {
	if o == nil || IsNil(o.Inputs) {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *ConversationAppendRequest) HasInputs() bool {
	if o != nil && !IsNil(o.Inputs) {
		return true
	}

	return false
}

// SetInputs gets a reference to the given ConversationInputs and assigns it to the Inputs field.
func (o *ConversationAppendRequest) SetInputs(v ConversationInputs) {
	o.Inputs = &v
}

// GetStore returns the Store field value if set, zero value otherwise.
func (o *ConversationAppendRequest) GetStore() bool {
	if o == nil || IsNil(o.Store) {
		var ret bool
		return ret
	}
	return *o.Store
}

// GetStoreOk returns a tuple with the Store field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationAppendRequest) GetStoreOk() (*bool, bool) {
	if o == nil || IsNil(o.Store) {
		return nil, false
	}
	return o.Store, true
}

// HasStore returns a boolean if a field has been set.
func (o *ConversationAppendRequest) HasStore() bool {
	if o != nil && !IsNil(o.Store) {
		return true
	}

	return false
}

// SetStore gets a reference to the given bool and assigns it to the Store field.
func (o *ConversationAppendRequest) SetStore(v bool) {
	o.Store = &v
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *ConversationAppendRequest) GetStream() bool {
	if o == nil || IsNil(o.Stream) {
		var ret bool
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationAppendRequest) GetStreamOk() (*bool, bool) {
	if o == nil || IsNil(o.Stream) {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *ConversationAppendRequest) HasStream() bool {
	if o != nil && !IsNil(o.Stream) {
		return true
	}

	return false
}

// SetStream gets a reference to the given bool and assigns it to the Stream field.
func (o *ConversationAppendRequest) SetStream(v bool) {
	o.Stream = &v
}

// GetToolConfirmations returns the ToolConfirmations field value if set, zero value otherwise.
func (o *ConversationAppendRequest) GetToolConfirmations() []ToolCallConfirmation {
	if o == nil || IsNil(o.ToolConfirmations) {
		var ret []ToolCallConfirmation
		return ret
	}
	return o.ToolConfirmations
}

// GetToolConfirmationsOk returns a tuple with the ToolConfirmations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConversationAppendRequest) GetToolConfirmationsOk() ([]ToolCallConfirmation, bool) {
	if o == nil || IsNil(o.ToolConfirmations) {
		return nil, false
	}
	return o.ToolConfirmations, true
}

// HasToolConfirmations returns a boolean if a field has been set.
func (o *ConversationAppendRequest) HasToolConfirmations() bool {
	if o != nil && !IsNil(o.ToolConfirmations) {
		return true
	}

	return false
}

// SetToolConfirmations gets a reference to the given []ToolCallConfirmation and assigns it to the ToolConfirmations field.
func (o *ConversationAppendRequest) SetToolConfirmations(v []ToolCallConfirmation) {
	o.ToolConfirmations = v
}

func (o ConversationAppendRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConversationAppendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompletionArgs) {
		toSerialize["completion_args"] = o.CompletionArgs
	}
	if !IsNil(o.HandoffExecution) {
		toSerialize["handoff_execution"] = o.HandoffExecution
	}
	if !IsNil(o.Inputs) {
		toSerialize["inputs"] = o.Inputs
	}
	if !IsNil(o.Store) {
		toSerialize["store"] = o.Store
	}
	if !IsNil(o.Stream) {
		toSerialize["stream"] = o.Stream
	}
	if !IsNil(o.ToolConfirmations) {
		toSerialize["tool_confirmations"] = o.ToolConfirmations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConversationAppendRequest) UnmarshalJSON(data []byte) (err error) {
	varConversationAppendRequest := _ConversationAppendRequest{}

	err = json.Unmarshal(data, &varConversationAppendRequest)

	if err != nil {
		return err
	}

	*o = ConversationAppendRequest(varConversationAppendRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "completion_args")
		delete(additionalProperties, "handoff_execution")
		delete(additionalProperties, "inputs")
		delete(additionalProperties, "store")
		delete(additionalProperties, "stream")
		delete(additionalProperties, "tool_confirmations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConversationAppendRequest struct {
	value *ConversationAppendRequest
	isSet bool
}

func (v NullableConversationAppendRequest) Get() *ConversationAppendRequest {
	return v.value
}

func (v *NullableConversationAppendRequest) Set(val *ConversationAppendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConversationAppendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConversationAppendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConversationAppendRequest(val *ConversationAppendRequest) *NullableConversationAppendRequest {
	return &NullableConversationAppendRequest{value: val, isSet: true}
}

func (v NullableConversationAppendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConversationAppendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
