/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistralai

import (
	"encoding/json"
	"fmt"
)

// checks if the ListFilesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListFilesResponse{}

// ListFilesResponse struct for ListFilesResponse
type ListFilesResponse struct {
	Data []FileSchema `json:"data"`
	Object string `json:"object"`
	Total NullableInt32 `json:"total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListFilesResponse ListFilesResponse

// NewListFilesResponse instantiates a new ListFilesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListFilesResponse(data []FileSchema, object string) *ListFilesResponse {
	this := ListFilesResponse{}
	this.Data = data
	this.Object = object
	return &this
}

// NewListFilesResponseWithDefaults instantiates a new ListFilesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListFilesResponseWithDefaults() *ListFilesResponse {
	this := ListFilesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListFilesResponse) GetData() []FileSchema {
	if o == nil {
		var ret []FileSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListFilesResponse) GetDataOk() ([]FileSchema, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListFilesResponse) SetData(v []FileSchema) {
	o.Data = v
}

// GetObject returns the Object field value
func (o *ListFilesResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ListFilesResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ListFilesResponse) SetObject(v string) {
	o.Object = v
}

// GetTotal returns the Total field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListFilesResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total.Get()) {
		var ret int32
		return ret
	}
	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFilesResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// HasTotal returns a boolean if a field has been set.
func (o *ListFilesResponse) HasTotal() bool {
	if o != nil && o.Total.IsSet() {
		return true
	}

	return false
}

// SetTotal gets a reference to the given NullableInt32 and assigns it to the Total field.
func (o *ListFilesResponse) SetTotal(v int32) {
	o.Total.Set(&v)
}
// SetTotalNil sets the value for Total to be an explicit nil
func (o *ListFilesResponse) SetTotalNil() {
	o.Total.Set(nil)
}

// UnsetTotal ensures that no value is present for Total, not even an explicit nil
func (o *ListFilesResponse) UnsetTotal() {
	o.Total.Unset()
}

func (o ListFilesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListFilesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["object"] = o.Object
	if o.Total.IsSet() {
		toSerialize["total"] = o.Total.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListFilesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListFilesResponse := _ListFilesResponse{}

	err = json.Unmarshal(data, &varListFilesResponse)

	if err != nil {
		return err
	}

	*o = ListFilesResponse(varListFilesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "object")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListFilesResponse struct {
	value *ListFilesResponse
	isSet bool
}

func (v NullableListFilesResponse) Get() *ListFilesResponse {
	return v.value
}

func (v *NullableListFilesResponse) Set(val *ListFilesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListFilesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListFilesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListFilesResponse(val *ListFilesResponse) *NullableListFilesResponse {
	return &NullableListFilesResponse{value: val, isSet: true}
}

func (v NullableListFilesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListFilesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
